### ISSUE TITLE
[Bug] VC connectivity

### ISSUE THREAD

**Issue by MrZeroLord** [Aliucord/Aliucord#101]
When you join a vc everything is nice and you are able to connect. 
But if you are getting dragged from that vc into another one your client will just tell you that you are disconnected and you wont connect to the new one. 

This makes it impossible to talk in channels which you cant see.

**Comment by TymanWasTaken** [comment]
Does this happen on stock discord?

**Comment by MrZeroLord** [comment]
If you mean by stock Discord the official versions, no. 
Works fine with the Beta I'm using

**Comment by Vendicated** [comment]
try it on the same version Aliucord uses https://aliucord.com/download/discord?v=89108

**Comment by MrZeroLord** [comment]
Seems like my discord has just been weird? Tried it twice and it wouldn't work, tried it now once and it does work...

Thanks though for your boths help!
