### ISSUE TITLE
FDroid release?

### ISSUE THREAD

**Issue by solonovamax** [Aliucord/Aliucord#107]
Would it be possible to get an fdroid release up, or is that not an option?
Because that'd be sick.

**Comment by hairyfred** [comment]
Aliucord Installer is agaisnt fdroids guidelines
Having its own repo to be added manually is pointless as Aliucord installer can update itself

**Comment by solonovamax** [comment]
@hairyfred pain

Oh well

**Comment by solonovamax** [comment]
I'm trying to figure out how to close it on fasthub, gimme a sec.
