### ISSUE TITLE
Xposed support to avoid repacking APK

### ISSUE THREAD

**Issue by raisehero** [Aliucord/Aliucord#109]
### What is it that you'd like to see?

Xposed allows modification without repacking APK file.

### Go into more detail...

Like WA tweaker, this allows updates to Discord patches to be updated without restarting the device or reinstalling the APK.

This allows patching the currently Discord APK without installing a separate Aliucord-patched Discord app

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Hades785** [comment]
Aliucord already has a WIP Xposed module: https://github.com/Aliucord/DiscordThemer
Right now the Themer plug-in is more recommended though iirc.

**Comment by Juby210** [comment]
Sorry that's not really possible because xposed doesn't allow you to access hooked app classes directly like we do.
