### ISSUE TITLE
Occasional crashing on startup after 96.3 update

### ISSUE THREAD

**Issue by snappyapple632** [Aliucord/Aliucord#113]
### Discord Account

snappyapple632#0632

### What happens when the bug or crash occurs?

When opening Aliucord, the app may occasionally crash. These crashes appear to be random.

### What is the expected behaviour?

Aliucord should not crash on startup.

### How do you recreate this bug or crash?

1. Force stop Aliucord
2. Start Aliucord
3. Repeat if crash does not occur (or use RestartButton if installed).
4. The app should crash upon startup.

### Crash-log

```
This crash does not generate a log within Aliucord. Here is a logcat instead: 
[logs-2021-10-09-14-33-49.zip](https://github.com/Aliucord/Aliucord/files/7316487/logs-2021-10-09-14-33-49.zip)

```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
these crashes are native crashes which can be found on line 1020 and 1598. Both of them occurred in "FrescoDecodeExe". Fresco is a library discord uses for image stuff, so this is a stock discord issue and not Aliucord's fault. Sadly not much can be done, let's hope Discord/Facebook fix it soon

**Comment by snappyapple632** [comment]
I'm now 95% certain the issue is being caused by Better mediaViewer. I will take this issue to zt.
