### ISSUE TITLE
Add a "Disable MIUI optimizaiton" window for people that use m*ui

### ISSUE THREAD

**Issue by RGBCube** [Aliucord/Aliucord#172]
### Discord Account

RGBCube#4777

### What is it that you'd like to see?

the title. Vanced manager has this feature

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by X1nto** [comment]
hi studio

**Comment by ItzOnlyAnimal** [comment]
hi studio

**Comment by Vendicated** [comment]
miui works fine with it enabled
