### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by IndiaPlayz** [Aliucord/Aliucord#178]
### Tell us all about it.

WilL My Discord ID will be banned to Use This Modded Discord

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by Juby210** [comment]
![image](https://user-images.githubusercontent.com/31005896/146641201-c818cff9-0f75-4918-95cb-02c079962078.png)
Read our faq on our discord's server https://discord.gg/aliucord
