### ISSUE TITLE
CrashRecovery but for Aliucord

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/Aliucord#18]
### Description
A feature to recover from crashes caused by plugins. Or at least show the error that it is causing, plus some debug information

### More info
Most of time you need to use logcat or something to get the debug information from Aliucord: if a plugin fails, if its a bug from Aliucord, etc. Sadly, logcat is root-only. Yeah there is the adb debugger, but you'll need to have a computer, and most of the phone users don't have a computer at all. So my suggestion is a plugin that gets those logs when aliucord crashes.

Useful links: https://stackoverflow.com/questions/32229170/catch-all-possible-android-exception-globally-and-reload-application

**Comment by Juby210** [comment]
Can be closed due to 6d072250fa1e026d773546fb381c2ecc4337cb3a.
