### ISSUE TITLE
i cant join the support server

### ISSUE THREAD

**Issue by Dxrkzen** [Aliucord/Aliucord#186]
### Tell us all about it.

I try to join the server I can't join my account is 25 days old because I got disabled recently (25 days ago) On the account I was like 230 days old. I wanna join the server but I can't. User I'd: 914934929069072414

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by hairyfred** [comment]
1. This is really not the way
2. It just said 914934929069072414 joined and left, no ban/kick

**Comment by hairyfred** [comment]
https://cdn.discordapp.com/attachments/811262084968742932/924810442969346048/unknown.png
Your previous account was banned due to selfbotting
