### ISSUE TITLE
Discord Support Server

### ISSUE THREAD

**Issue by blakydisc** [Aliucord/Aliucord#193]
### Tell us all about it.

Recently I came across Aliucord again and was going to join the support server for the list of plugins, but when I went to join, it wasn't letting me so I checked to see if I could join another in which it did, but I couldn't join Aliucord's. I went on Desktop browser mode and it said that I was banned. I don't recall getting banned last time I was in it / why I got banned. My username has changed recently - its currently NotAndrew#3853, I believe it was SmellySocks420#3853 before.

If someone could get back to me on this, that'd be great.

### Request Agreement

- [x] I did indeed check to make sure the issue is original!

**Comment by hairyfred** [comment]
These unban issues need to stop, this is not what the repo is for, if your going to do it, use an existing issue about it, it just clutters up the repo
