### ISSUE TITLE
Add ability to share plugin folder

### ISSUE THREAD

**Issue by adrifcastr** [Aliucord/Aliucord#195]
### Discord Account

Quality#0001

### What is it that you'd like to see?

It'd be great to be able to share and apply the entire plugin folder.

### Go into more detail...

I'm aware one can simply zip the folder and upload it - however - It'd be nice to just add an extra button to the file upload screen that zips the plugin folder and selects it as attachment, then in similar fashion to how the plugin installation already works, when long pressing a plugin pack, it'll install the entire thing.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Vendicated** [comment]
useless feature that you can simply do by zipping the folder and unzipping it elsewhere. Also promotes installing plugins without knowing what they, sharing plugins in bulk and possibly sending malicious plugins
