### ISSUE TITLE
Add option to disable missing manifest error

### ISSUE THREAD

**Issue by MulverineX** [Aliucord/Aliucord#197]
### Discord Account

MulverineX#\0\0\01

### What is it that you'd like to see?

The bottom toast thing telling you of missing manifests is super annoying when you have lots of plugins missing it. It blocks acceas to some keyboard keys & some of the plugins still work. The option would let you disable these toasts.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by zt64** [comment]
Any plugins saying this error have not been updated for latest version. Just uninstall them

**Comment by Vendicated** [comment]
As mentioned by zt these plugins are outdated and no longer able to be loaded so disabling this warning would be a very bad way of dealing with them. Instead they could automatically be removed
