### ISSUE TITLE
Bridged Matrix Space

### ISSUE THREAD

**Issue by hiddeninthesand** [Aliucord/Aliucord#204]
### What is it that you'd like to see?

Currently, only a single Matrix room is bridged to the Discord server, with no notable importance to it whatsoever for developmental or social communication. Creating a Space and bridging more of the helpful channels (such as support, development channels, or even the recreational social channels) could make the project easier to develop for. Ideally, the same could be applied to IRC and Telegram.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Vendicated** [comment]
Aliucord is a mod for the discord app, so it makes very little sense to have conversation anywhere but on discord. If you don't use Discord, there is no point talking on the Aliucord server. The bridge channel that has these bridges is mainly for shits and giggles, and if it were bridged to serious channels, people would just abuse it to spam or ban evade

**Comment by Pantyhose-X** [comment]
> Aliucord is a mod for the discord app, so it makes very little sense to have conversation anywhere but on discord. If you don't use Discord, there is no point talking on the Aliucord server. The bridge channel that has these bridges is mainly for shits and giggles, and if it were bridged to serious channels, people would just abuse it to spam or ban evade

I want to bridge all discord messages to an matrix server, but I'm not the administrator of the server, and I don't have a way to add a bot to each discord server.
discord api 
Maybe help? https://matrix.org/ecosystem/bridges/discord/
