### ISSUE TITLE
Manually downloaded plugin does not show up in list

### ISSUE THREAD

**Issue by illusion0001** [Aliucord/Aliucord#207]
### Discord Account

illusion#3185

### What happens when the bug or crash occurs?

Manually installing a pack of plugin from a previous install or elsewhere into `Aliucord/plugins` does not show up in the plugin list.

### What is the expected behaviour?

Expected behaviour should show the manually installed plugins 

### How do you recreate this bug or crash?

1. Download a plugin manually (i.e https://github.com/RhythmLunatic/aliucord-plugins#copy-instead-of-share-images) https://github.com/RhythmLunatic/aliucord-plugins/raw/builds/CopyInsteadOfShareImages.zip
2. Place into `Aliucord/plugins`
3. Open Aliucord and check Plugins

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by scrazzz** [comment]
Did you restart Aliucord after moving the plugin into the plugins folder?

**Comment by illusion0001** [comment]
Just tried that and it worked, but the downloader doesn't require the restart though

**Comment by Vendicated** [comment]
because the downloader automatically loads it for you. If you install manually you have to restart once, that is the intended behaviour
