### ISSUE TITLE
i got banned which wasn't my mistake

### ISSUE THREAD

**Issue by harrynotfound** [Aliucord/Aliucord#212]
### Tell us all about it.

So few days ago i got hacked which i didn't knew I did ,the hacker just sent his links everywhere typed @. Everyone , in the servers i have been modding on , and I got banned from aliucord server when i was actually not using aliucord , which means I can't even get plugins i tryed to tell that to ven but he/she blocked me , this was the only way I could be unbanned 

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by harrynotfound** [comment]
I got banned from it for sending the fake link, which actually the hacker did and my acc is fine now I have 2fa aswell with new password

**Comment by scrazzz** [comment]
~~skill issue~~
You are responsible for what happens on your account. There's no point in blaming the "hacker" since it's your fault at the end of the day. 

Also, GitHub issues isn't the place for ban appeals.

**Comment by YoussefBedwarspro** [comment]
Oh that's bad

**Comment by YoussefBedwarspro** [comment]
What do you mean?

**Comment by YoussefBedwarspro** [comment]
I am not a hacker
