### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by K0N44** [Aliucord/Aliucord#216]
### Discord Account

𝙄𝙉𝙀𝙁𝙁𝘼𝘽𝙇𝙀𝑅𝑂𝑆𝐸#3755

### What happens when the bug or crash occurs?

I can't join your server, when i press Accept Invite it doesn't work please answer me

### What is the expected behaviour?

It's amazing

### How do you recreate this bug or crash?

I press Accept Invite
Then it doesn't work

### Crash-log

```
Replace this text with your crash-log.
```
Please

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by ItzOnlyAnimal** [comment]
not a bug you're just banned lmao

**Comment by K0N44** [comment]
> not a bug you're just banned lmao

Lol, but i can join any server only Aliucord server
