### ISSUE TITLE
[Feature Request] Notification support without Google Play Services

### ISSUE THREAD

**Issue by Mnky313** [Aliucord/Aliucord#223]
### What is it that you'd like to see?

For people with dogoogled android devices. (Discord doesn't send notifications without play services normally).

It would be awesome but I'm not sure if its really possible.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by ItzOnlyAnimal** [comment]
Not possible with Aliucord itself to my knowledge

**Comment by Vendicated** [comment]
It may be possible but out of the scope of Aliucord and a very niche feature that would add a lot of code to Aliucord that only a small portion of the user base would use. It should rather be a plugin. 

Additionally, doing this would require a permanent gateway connection which will cause high battery drain.

Your best bet is probably installing [microg](https://microg.org/) a foss Google play services replacement
