### ISSUE TITLE
Feature Request: custom notification icon/color

### ISSUE THREAD

**Issue by JapanYoshi** [Aliucord/Aliucord#224]
### Discord Account

@hai!touch Studios#1967

### What is it that you'd like to see?

I use both the original Discord app and Aliucord on different accounts, and it gets confusing when both the apps send notifications.

On AppCloner, you can change the icon and color of the notifications, which makes it a lot easier to tell my Discord notifications apart:
![Screenshot_20220311_201435](https://user-images.githubusercontent.com/8707990/157857294-ffbc57fe-57fb-4726-b783-98ecc37a0aaf.png)

### Go into more detail...

It would be great if Aliucord had a default icon and color that’s different from the original. But it would be even cooler if the user could customize them in the manager before building the Aliucord app!

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Vendicated** [comment]
https://github.com/Aliucord/plugin-requests
