### ISSUE TITLE
Server About Me

### ISSUE THREAD

**Issue by JBugelLOL** [Aliucord/Aliucord#225]
### Discord Account

JBUGΞL#0812

### What is it that you'd like to see?

Server-AboutMe!

### Go into more detail...

Same as on the Desktop-Version. Getting the ability to change the Server AboutMe

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by taskylizard** [comment]
You should request this in [plugin-requests](https://github.com/Aliucord/plugin-requests) instead.
