### ISSUE TITLE
[Feature Request] Xposed Module

### ISSUE THREAD

**Issue by puiemonta1234** [Aliucord/Aliucord#227]
### What is it that you'd like to see?

With the new switch to LSPlant, I wonder if it's possible to also make an Aliucord Xposed / LSPosed module, for easier installation for rooted users.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Juby210** [comment]
Not possible, xposed doesn't run modules in same context and class loader as the base app. We need the same context and class loader to extend and access classes from normal discord without reflection.
