### ISSUE TITLE
Slash command makes app unresponsive 

### ISSUE THREAD

**Issue by cutterchop** [Aliucord/Aliucord#228]
### Discord Account

CutterChop#1893 

### What happens when the bug or crash occurs?

When you input a aliucord plugin only it decides to go non responsive and then turns the app off without notice or crash log, this was reported before but it appears devs in discord say it was fixed before so it was removed from known issues, here it is back again hopefully someone comes up and help, I got a Huawei mate 10 lite and I am on the latest update 120 this bug only happens with aliucord plugins, the log cat won't read the error maybe it's cuz of my phone limitation so someone else prob would have a more accurate log to share 

### What is the expected behaviour?

I expect the command to initiate 

### How do you recreate this bug or crash?

You can't replicate on all phones it most probably would happen on a Huawei or OPPO phone 

### Crash-log

The app won't give a crash log on this scenario 

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
cant repro anymore
