### ISSUE TITLE
Aliucord crashed on oppo phone

### ISSUE THREAD

**Issue by xArnold-Lightx** [Aliucord/Aliucord#229]
### Discord Account

Arnold's XD#2225

### What happens when the bug or crash occurs?

Well the app itself just keep stuck at splash art discord and then started crashing even i try to reinstall it still same thing was running in color os 7.1 

### What is the expected behaviour?

Well the app itself I can't doing anything when I first open app and then it just stuck and crashing it.

### How do you recreate this bug or crash?

1. Get some phone oppo like oppo A5 2020
2. And install aliucord app
3. And open app
4. It the phone emulator can open easily so it was my phone slow or something and crashing the app.

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by hiromon211** [comment]
Same as mine, but on a Huawei device

**Comment by ItzOnlyAnimal** [comment]
as far as i can tell this just got fixed, update your installer and reinstall aliucord

**Comment by xArnold-Lightx** [comment]
> as far as i can tell this just got fixed, update your installer and reinstall aliucord

Umm yeah I know but the issues is the app itself loading endless and then crashing I have video that bug here

https://user-images.githubusercontent.com/101584314/160275309-32cb9620-b499-4f28-a282-2395f1f631a3.mp4

**Comment by Vendicated** [comment]
Update your installer and install Aliucord again
