### ISSUE TITLE
Stuck at Splash Screen (Huawei Device)

### ISSUE THREAD

**Issue by hiromon211** [Aliucord/Aliucord#230]
### Discord Account

Hiromon#4640

### What happens when the bug or crash occurs?

The app stucks at Splash Screen, I already saw someone had this but in an oppo device (that has been resolved), but in my case, in a Huawei device (Huawei Y6s 2019 to be specific). And yes, I updated Aliucord.

### What is the expected behaviour?

I expected to open the app normally.

### How do you recreate this bug or crash?

1. Grab a Huawei Device (or my Huawei model).
2. Open the app.
3. Wait until something pops that it's not responding.

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
Please upload a bugreport (adb bugreport or bug report option in developer options of your phone) or logcat (https://wiki.lineageos.org/how-to/logcat)

**Comment by hiromon211** [comment]
It magically fixes itself now, Idk what happened but yeah, thanks

**Comment by HalogenGam3r** [comment]
Can someone close this issue?
