### ISSUE TITLE
Patcher is "borked"

### ISSUE THREAD

**Issue by Dasher-droid** [Aliucord/Aliucord#231]
### What happens when the bug or crash occurs?

The bug happens when installer starts patching apk.
No additional information. Installer pretends to patch apk just fine. And patched apk is either NOT patched or broken that it cannot be installed. Sometimes it can't even detect that this is a package.

### What is the expected behaviour?

Patch apk and output patched apk that's with a green icon (instead of Android placeholder icon or stock discord one). Apk name should be aliucord, not discord-beta or com.discord.

### How do you recreate this bug or crash?

Device info:
Redmi note 8T 4/64gb
Arcana os custom ROM, Android 12 (not 12.1)
Rooted w/magisk

1. Go in aliucord installer
2. Get apk method: download
3. Aliucord installer patches apk
4. Apk is borked

### Crash-log

```
Checking cached apk..
Downloading Injector.dex..
Done
Downloading patched AndroidManifest.xml..
Done
Copying original apk (/data/user/0/com.aliucord.installer/cache/discord.apk)
Repacking apk
Replacing icons
Signing apk file
```
![Screenshot_20220331-095225_Package installer](https://user-images.githubusercontent.com/78162801/160985769-13e32d9f-9ada-473e-8209-2fc1af0c0c0c.png)

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
just run installer again

**Comment by BrickerAsked** [comment]
> 

Cannot, it does it all over again

**Comment by BrickerAsked** [comment]
Yes, it breaks apk every time

**Comment by Drownbywind** [comment]
Clear installer cache in app and in settings
