### ISSUE TITLE
not downloading

### ISSUE THREAD

**Issue by IsaiahHerrickYT** [Aliucord/Aliucord#233]
### What happens when the bug or crash occurs?

when I was trying to download aliucord from the installer it was not working the Split Apk Installer said there was no AndroidManifest.xml file

### What is the expected behaviour?

to download

### How do you recreate this bug or crash?

I do not know

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
this is not a bug. Use our support channel.
