### ISSUE TITLE
Aliucord's Download Connection Failed

### ISSUE THREAD

**Issue by TheGoldenSun** [Aliucord/Aliucord#244]
### Discord Account

Fukui#6495

### What happens when the bug or crash occurs?

My Wi-Fi connection is working fine it's just within the Aliucord app itself when trying to download the updated discord version it suddenly fails for some reason, I'm using Android 11 so I hope you guys can find a way to fix this
![Screenshot_20220514_101441](https://user-images.githubusercontent.com/104534608/168429675-b4faf453-0c5a-49ec-803d-152e031ae78f.png)

### What is the expected behaviour?

I expect that Aliucord should be able to allow itself to download faster rather than keeping android 11 users waiting for a while until it's finished. 

### How do you recreate this bug or crash?

1. I downloaded the updated version of Aliucord twice 
2. It says HttpException: Connection closed while receiving data

### Crash-log

Checking cached apk..
Downloading discord apk..
HttpException: Connection closed while receiving data, uri = https://rr2---sn-ab5sznz6.gvt1.com/play-apps-download-default/download/by-id/AF3DWBfkGpzLDiMDFxTo4XhicYUCStAldu_bYSMV_CIXaT0cwvNlTPxZC1pZdAmxulBWwtTm9KEKWPXC57oX9g2O-fAPjtSyPWos--6bwiTah_JL_RJBPsQ5NsTBPwxp88ZS74j1wdPmQSVqcKdf21QNJlbjtrOt0A?cpn=oZaBGWvHhfp9KrtZ&ctier=L&initcwndbps=14420&mh=pZ&mm=31&mn=sn-ab5sznz6&ms=au&mt=1652536863&mv=m&mvi=2&pl=16&expire=1652710415&ip=67.245.224.214&ipbits=0&sparams=expire,ipbits,ip,q:,initcwndbps,mh,mm,mn,ms,mv,mvi,pl,ctier&signature=6B96EF9C485EEA4112BA1F169624E41F3E000CC3.9953F9CAD93E6E568A36165845AF3BD3F5C18C32&key=am3

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
Internet issue on your end or the server, died for a second

**Comment by TheGoldenSun** [comment]
No my internet is working fine I think it's probably your server died


 
 
  On Sat, May 14, 2022 at 10:38 AM, ***@***.***> wrote:   


Internet issue on your end or the server, died for a second

**Comment by Vendicated** [comment]
it's not our server it's Google's. Again nothing we can fix and I can't reproduce it

**Comment by TheGoldenSun** [comment]
Not a problem for me since I was responsible to report this as an issue, thank you for telling me  
 
  On Sat, May 14, 2022 at 10:41 AM, ***@***.***> wrote:   


it's not our server it's Google's. Again nothing we can fix and I can't reproduce it

**Comment by TheGoldenSun** [comment]
Pardon me from intruding but the reply notification that's labeled as beta for your Aliucord is also an issue some Aliucord users is facing since some replies doesn't load faster to send it to other users.  
 
  On Sat, May 14, 2022 at 10:41 AM, ***@***.***> wrote:   


it's not our server it's Google's. Again nothing we can fix and I can't reproduce it

**Comment by Robin-Sch** [comment]
same error for me
