### ISSUE TITLE
[Feature Request] Launch Option

### ISSUE THREAD

**Issue by gghhkm** [Aliucord/Aliucord#246]
### Discord Account

gghhkm#9168

### What is it that you'd like to see?

Add a launch option for Aliucord in the Installer.

### Go into more detail...

Two possible locations to put the launch button to launch Aliucord.
![Screenshot_20220524-002202__01](https://user-images.githubusercontent.com/72711094/169948508-65d328ee-3034-4d59-8763-14e33263e10a.jpg)

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by zt64** [comment]
The upcoming Aliucord Manager has this
