### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NATURO7x** [Aliucord/Aliucord#248]
### Discord Account

NATURO7x#9158

### What happens when the bug or crash occurs?

![Screenshot_2022-06-02-12-57-32-417_com google android packageinstaller](https://user-images.githubusercontent.com/101972067/171595260-6f7c5128-1cd2-419a-9489-d35a98cea417.jpg)
![Screenshot_2022-06-02-13-15-20-428_com google android packageinstaller](https://user-images.githubusercontent.com/101972067/171595271-3c72295c-7d48-4b58-b381-abcc0ce566af.jpg)
![Screenshot_2022-06-02-13-15-34-720_com google android packageinstaller](https://user-images.githubusercontent.com/101972067/171595278-353685f8-67f2-4fdd-8b97-4d4fc552abc2.jpg)
This is my problem

### What is the expected behaviour?

It's need to install alicord not discord

### How do you recreate this bug or crash?

It's not Installing property

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by GangsterFox** [comment]
1. Please use the support channel instead of github issues
2. Are you using a support android version(7+)?
