### ISSUE TITLE
When installing the Aliucord Installer, I get App not installed.

### ISSUE THREAD

**Issue by ANDREI12333** [Aliucord/Aliucord#249]
### Discord Account

ANDREI12333#3094

### What happens when the bug or crash occurs?

When trying to install the aliucord installer, getting a app not installed error.

### What is the expected behaviour?

I expect the installer to install and this bug is preventing the system from installing aliucord

### How do you recreate this bug or crash?

1. Download the "Installer-release.apk"
2. Try to insall it
3. See error.

### Crash-log

I'm unable to provide a crash-log, As this is NOT a crash.

### Request Agreement

- [x] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
Please go the #support channel in the Aliucord Discord server

**Comment by ANDREI12333** [comment]
I've sloved it my device didn't have enough storage

**Comment by ANDREI12333** [comment]
When installing it with "Split APKs Installer" i get "Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{somecode:com.aeyr.sai/u9a121} (pid=17566, uid=10121) that is not exported from uid 10564"

**Comment by ANDREI12333** [comment]
When installing the Aliucord app not the installer btw..
