### ISSUE TITLE
Embeds not appearing

### ISSUE THREAD

**Issue by Johannes7k75** [Aliucord/Aliucord#250]
### Discord Account

Johannes7k75#0689

### What happens when the bug or crash occurs?

The bug occurs on every embed i want to see.
Github Webhook ambed, embeds send by a bot.

P.s: I also disabled all Plugins to test and even then the embede doesnt render

### What is the expected behaviour?

The embed gets shown e.g. Title, Description, Color and/or footer

### How do you recreate this bug or crash?

1. Open Discord
2. Get in any channel with an embed
3. Dont see the embed rendered 

### Crash-log

```
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by ItzOnlyAnimal** [comment]
not an aliucord issue![Screenshot_20220623-005352.png](https://user-images.githubusercontent.com/24845294/175214442-6d7ada8b-25f3-47e2-a31d-00d14a7437dd.png)

**Comment by DiamondMiner88** [comment]
0iq

**Comment by Johannes7k75** [comment]
Thanks. 
I thought that switch was for something different. My fault
