### ISSUE TITLE
Aliucord keeps loading forever on the android 12.1 june patch

### ISSUE THREAD

**Issue by AldairbotHerotaku** [Aliucord/Aliucord#251]
I recently updated from the android 12.1 may patch to the june patch.
In the may patch everything worked fine but since i updated the app keeps loading forever in a gray screen with the aliucord logo, i tried cleaning my data, uninstalling, reinstalling and delete the aliucord folder

https://user-images.githubusercontent.com/52483168/175829541-11cdb243-4ded-45f6-bb46-fe6e7af97e86.mp4

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by Vendicated** [comment]
Please upload a logcat

**Comment by AldairbotHerotaku** [comment]
> Please upload a logcat

I need to run logcat with adb and paste the logs right?

**Comment by DiamondMiner88** [comment]
yes

**Comment by AldairbotHerotaku** [comment]
I wanted to upload the logs but it magically seemed to work again
