### ISSUE TITLE
Pixel Launcher themed icons support

### ISSUE THREAD

**Issue by ItsLynix** [Aliucord/Aliucord#252]
### Discord Account

Lynix#2025

### What is it that you'd like to see?

Alright so, the Google Pixel Launcher has this features where it allows apps to have themed icons following the device's current Monet (Material You) color scheme.

Normal discord has support for this and its icon is themed accordingly, but Aliucord since the icon has been modified, does not support this feature.

Is there a possibility that this will be added eventually?

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by ItsLynix** [comment]
![Screenshot_20220630-100440_Pixel Launcher](https://user-images.githubusercontent.com/71310187/176625843-80fda804-1868-495c-8a78-4b7da2e9fbd2.png)

**Comment by ItsLynix** [comment]
Actually wait, I just realized this might just work as an additional alternative setting to #87

**Comment by Vendicated** [comment]
Go into installer settings and unselect replace icon

**Comment by ItsLynix** [comment]
> Go into installer settings and unselect replace icon and reinstall Aliucord using it

This did not apply theming to the icon.

**Comment by Vendicated** [comment]
Because Discord does not implement adaptive themeing, its your icon pack changing discords icon

**Comment by ItsLynix** [comment]
Well, unfortunately it's not that easy.
I can't really request an icon for the pixel launcher, because pixel launcher doesn't really support icon packs. It's locked to google's own pack that is hard coded into pixel launcher. Themed icons is Google's feature for their launcher. The only way I see to get the themed discord icon on Aliucord I guess would be to make the package name the same as discord's so it applies the same icon to it.

**Comment by ItzOnlyAnimal** [comment]
> Well, unfortunately it's not that easy. I can't really request an icon for the pixel launcher, because pixel launcher doesn't really support icon packs. It's locked to google's own pack that is hard coded into pixel launcher. Themed icons is Google's feature for their launcher. The only way I see to get the themed discord icon on Aliucord I guess would be to make the package name the same as discord's so it applies the same icon to it.

If you don't mind switching launchers, just use [Lawnchair](https://lawnchair.app). It has themed icons support for many more apps than just google's selection
Or tell @zt64 to finish manager, then you can set package name to whatever & thus have themed icons through whatever means necessary

**Comment by zt64** [comment]
Guhhh finish React Native

**Comment by DiamondMiner88** [comment]
https://github.com/Aliucord/AliucordManager/issues/37 themed icons soon
