### ISSUE TITLE
idk where to ask

### ISSUE THREAD

**Issue by Tharki-God** [Aliucord/Aliucord#256]
### Tell us all about it.

unban in support server.
banned with reason
  You have been banned from Server: Aliuwucord
For Reason: weird and inappropriate video and stupid username
the video for context.
just a meme.
https://user-images.githubusercontent.com/73281112/178627745-bca1bce9-8555-4941-a1a5-01734d709c6a.mp4
please unban
username: LoneWeeb-SexToys#0480

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by ServOKio** [comment]
<hr/>
Thank you for writing to us! Our team has carefully considered your question and, unfortunately, we cannot remove lock from your account at the moment.


Your nickname advertises another company whose trademark does not relate to [our products](https://github.com/mantikafasi/AliucordPlugins/tree/main/Vibrator2) in any way. Please change your nickname and we will try to help you in near future.

Tironze,
The Aliucord Team
<hr/>

**Comment by ItzOnlyAnimal** [comment]
<hr>
Hi John,

Thanks for the reply.

As of this writing, I have already changed your tag. Please inform your followers to follow you again on your new tag.

Should you have any other queries, don't hesitate to contact me again. I am just a reply away. I hope I will meet you one day on the battle bus!

We appreciate your understanding about this matter.
</hr>

**Comment by Tharki-God** [comment]
what?

**Comment by DiamondMiner88** [comment]
---
HI John,
Thanks for the reply.

As of this writing, I have already gained full access over your Discord account and will proceed to post furry art in every channel you're in.

Best wishes,
rushii

**Comment by wingio** [comment]
Hi John,

DN

- The Aliucord Moderation Team

**Comment by MeFinity** [comment]
Hi John,
Delete your github account

- DN
