### ISSUE TITLE
Multiple accounts sign in

### ISSUE THREAD

**Issue by Loup-Garou911XD** [Aliucord/Aliucord#258]
### What is it that you'd like to see?

An option to quickly switch accounts.Like a new option on login page that uses tokens stored on device to sign in 

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by pras92** [comment]
Was this marked invalid due to the mention using tokens to support multiple accounts or multi login in itself isn't feasible?

**Comment by ItzOnlyAnimal** [comment]
<img src="https://cdn.discordapp.com/emojis/859796756111294474.webp?size=96&quality=lossless"/>Its because theres a plugin for it already

**Comment by Vendicated** [comment]
It was marked invalid because this is not the place to request plugins, plus that plugin already exists anyway

**Comment by Loup-Garou911XD** [comment]
> It was marked invalid because this is not the place to request plugins, plus that plugin already exists anyway

I would be thankful if you could guide me to the plugin
