### ISSUE TITLE
RPC Button Link Doesn't direct

### ISSUE THREAD

**Issue by zairullahdev** [Aliucord/Aliucord#259]
### What happens when the bug or crash occurs?

Literally when I'm click it and yea it's wont directing

### What is the expected behaviour?

It's open YouTube link

### How do you recreate this bug or crash?

Press button

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by MeFinity** [comment]
If youre talking about clicking your own RPC

This is discord's issue,you cannot click on your own RPC buttons for some reason


kindly close this request
