### ISSUE TITLE
Crash on Aliucord installer

### ISSUE THREAD

**Issue by Johannes7k75** [Aliucord/Aliucord#265]
### Discord Account

Johannes7k75#0689

### What happens when the bug or crash occurs?

The bug happens when i scroll down the commits and after a many commits it just crashes. 

### What is the expected behaviour?

To let me down to the first commit.

### How do you recreate this bug or crash?

1. Install the installer
2. Open the installer scroll down on the commits

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
invalid issue no log
