### ISSUE TITLE
Download from Google Play? 

### ISSUE THREAD

**Issue by StandingPadAnimations** [Aliucord/Aliucord#266]
### Tell us all about it.

Just curious, will Aliucord ever be downloadable from Google Play? Some people like myself can't install APKs due to restrictions. 

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by Vendicated** [comment]
No, against play store ToS

**Comment by StandingPadAnimations** [comment]
What's the best way to install Aliucord without APK permissions?

**Comment by OmegaSunkey** [comment]
1. give up

**Comment by OmegaSunkey** [comment]
there is no way to install apks without having install from unknown sources enabled

**Comment by OmegaSunkey** [comment]
ig you're using family link so ask your parents
