### ISSUE TITLE
INSTALL_FAILED_DEXOPT on 5th Generation Kindle Fire HD 8

### ISSUE THREAD

**Issue by MystiK791** [Aliucord/Aliucord#269]
### What happens when the bug or crash occurs?

When building Aliucord from the installer on my Kindle Fire, I get a "App Not Installed" error trying to install the built app. When I copied the APK to my PC and tried installing it through APK, I get an error that says "Failure [INSTALL_FAILED_DEXOPT]". 

### What is the expected behaviour?

I expect Aliucord to install

### How do you recreate this bug or crash?

1. Build Aliucord from the installer
2. Attempt to install it via ADB on a 5th generation Kindle Fire HD 8

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
Your device is way too old for aliucord. Please flash a newer rom or get an actual phone

**Comment by MystiK791** [comment]
> Your device is way too old for aliucord. Please flash a newer rom or get an actual phone

I have an actual phone. Plus, my kindle can run vanilla Discord just fine

**Comment by DiamondMiner88** [comment]
aliucord requires api >= 24 iirc which is higher than your kindle so 🤷

**Comment by TymanWasTaken** [comment]
Sdk 24 is android 7, and the kindle uses android 5.
Maintaining for old versions of android is really annoying and almost no one uses them, so there is no point in supporting versions that old.
