### ISSUE TITLE
Update base Discord app

### ISSUE THREAD

**Issue by Jaajounay** [Aliucord/Aliucord#271]
### Discord Account

@Singe Fan Account#1538 

### What is it that you'd like to see?

Aliucord uses an old version of discord. The latest version of discord has updated the user interface and added functionality I think it would be better to add this new version to Aliucord

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Juby210** [comment]
Check https://github.com/Aliucord/AliucordRN

**Comment by GangsterFox** [comment]
Bare in mind the Team isn't finished with it
