### ISSUE TITLE
Crashing on samsung galaxy J6

### ISSUE THREAD

**Issue by zvanm** [Aliucord/Aliucord#276]
### What happens when the bug or crash occurs?

It happens when i launch the app

### What is the expected behaviour?

Loadup client

### How do you recreate this bug or crash?

1. Install aliucord on j6
2. launch it

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
Use our support channel please
