### ISSUE TITLE
Not launching on my samsung j6 (please don't delete this post i already asked on the discord server)

### ISSUE THREAD

**Issue by zvanm** [Aliucord/Aliucord#279]
### What happens when the bug or crash occurs?

When i launch the app

### What is the expected behaviour?

I expect it to drop me on the client

### How do you recreate this bug or crash?

1. install on samsung j6
2. launch the app

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
Stop spamming issues without providing any useful info, you literally don't provide any logs so how we are supposed to help you.
