### ISSUE TITLE
More ways to install

### ISSUE THREAD

**Issue by GuraNotFound** [Aliucord/Aliucord#280]
### What is it that you'd like to see?

Is it possible to add the function of installing by root? I use Magisk a lot so I want to overwrite the original!

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by TymanWasTaken** [comment]
The ability to install using root is pointless for something like this
You can just uninstall the normal discord app and set the installer to not replace the app icon if you want
