### ISSUE TITLE
Aliucord's Application Issue

### ISSUE THREAD

**Issue by TheGoldenSun** [Aliucord/Aliucord#281]
### Discord Account

Fukui#6495

### What happens when the bug or crash occurs?

Aliucord appears to be a default version of regular discord.

### What is the expected behaviour?

Downloaded plugins remains unavailable since regular discord within aliucord is under default security by discord themselves.

![Screenshot_20221021_050839](https://user-images.githubusercontent.com/104534608/197160696-cc928cda-38e0-45bb-b688-746254edf3f0.png)
![Screenshot_20221021_050825](https://user-images.githubusercontent.com/104534608/197160703-707c0238-e9f6-4e79-90dc-f9f9cf91130e.png)

### How do you recreate this bug or crash?

1. Improve plug-in installment 
2. Improve aliucord
3. Improve Restart 
4. Improve aliucord security 

### Crash-log

```
No crash logs was provided since aliucord's stable version 126.21 was bugged before regular discord took over the aliucord application I had installed before to make it into their default security, only debugs was seen in aliucord only. 
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by UsedDiscord** [comment]
Your screenshot is useless...
Look at the bottom of Discord...
It will then be marked: App Information 126.21 STABLE (126021)
Aliucord EA1524C...

And also, you can find the Aliucord settings after the "App Settings" section of Discord
Take a photo of the section at the bottom of discord please thank you

![Screenshot_2022-10-21-12-02-23-359_com aliucord](https://user-images.githubusercontent.com/57113628/197170221-6816caf5-d942-448f-a173-21aedd9313f1.jpg)

![Screenshot_2022-10-21-12-02-06-957_com aliucord](https://user-images.githubusercontent.com/57113628/197170263-67456228-ae81-4bb3-b452-95dc95e3db61.jpg)

**Comment by TheGoldenSun** [comment]
![Screenshot_20221021_060642](https://user-images.githubusercontent.com/104534608/197171099-7785328e-0405-4b41-a5d2-7f0338abd5ea.png)

What were you saying about my proof of screenshot is useless?

**Comment by UsedDiscord** [comment]
The section you took, i.e.: User Settings and Billing Settings is the same everywhere, Aliucord, Bluecord or (little joke...): Discord
So clearly, the part of the screenshot was not interesting ^^'

Now concerning the fact that we can see that you don't have aliucord in the App Info section, it looks like the patch is not applied...

If you could join the Discord directly that would be better: [https://discord.gg/uwucord](https://discord.gg/uwucord) (I reassure, it's the official Aliucord discord...)

Section #support

If you can't join for X reason, could you give us the version of Android you currently have?

**Comment by TheGoldenSun** [comment]
Android 12, Galaxy a21

**Comment by Vendicated** [comment]
Github is not for support, please join our support server instead

**Comment by TheGoldenSun** [comment]
I never stated that this issue was for support but a bug issue.

**Comment by Vendicated** [comment]
okay but it's not a bug, it's an issue on your end. So use our support channel to get help figuring out what's the issue
