### ISSUE TITLE
Aliucord isn't responding.

### ISSUE THREAD

**Issue by Gorkido** [Aliucord/Aliucord#283]
### Discord Account

Gorkido#5163

### Device information

- Huawei EMUI Version: 12.0.0

### What happens when the bug or crash occurs?

The bug appears when i start Aliucord.

### What is the expected behaviour?

I expect Aliucord to start normally without any problems.

### How do you recreate this bug or crash?

1. Install the latest [Aliucord Installer](https://github.com/Aliucord/Aliucord/releases).
2. Install Aliucord via [Aliucord Installer](https://github.com/Aliucord/Aliucord/releases).
3. Start Aliucord.

<img src="https://user-images.githubusercontent.com/81165187/197348108-485e781b-6323-4897-9635-34bd0363c66b.jpg" height="400" width="200" />

https://user-images.githubusercontent.com/81165187/197348133-45f85b76-5b9a-472f-9474-5a6799038360.mp4

### Crash-log

**Aliucord** doesn't create any Crash Logs for me. 
"Crash Logs" folder doesn't exist in Aliucord's dir.

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
Please use the support channels in our Discord
