### ISSUE TITLE
hCaptcha does not open in browser

### ISSUE THREAD

**Issue by Taureon** [Aliucord/Aliucord#284]
### What happens when the bug or crash occurs?

When I try to log in I need to verify that I am a human.
The hCaptcha in the app does not work, so I click the button to open it in my Browser.
It just opens normal discord and then does nothing.

### What is the expected behaviour?

I expected Aliucord to open a new Tab in Chrome with an hCaptcha verification box in it.

### How do you recreate this bug or crash?

When prompted to do a bot check when trying to log in with email and password, there are two options: 1) Open in app. 2) Open im browser.

Simply press option 2.

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Taureon** [comment]
That didn't work at all because I needed to log in before I could change any setting.

**Comment by DiamondMiner88** [comment]
This is not an issue with aliucord
