### ISSUE TITLE
Discord Server Invite Not Working

### ISSUE THREAD

**Issue by HardNeos** [Aliucord/Aliucord#287]
### Discord Account

HardNeos#1537

### What happens when the bug or crash occurs?

The bug is that the discord server invite dosent work: when i click on the official discord server link discord.com/invite/EsNDvBaHVU i click on "accept invitation" and it does nothing. Can you fix this please?
![Screenshot_2022-12-09-17-10-55](https://user-images.githubusercontent.com/118657631/206744751-820ebcff-31c1-4c98-93dc-8e45e70dd922.jpg)
![Screenshot_2022-12-09-17-11-13](https://user-images.githubusercontent.com/118657631/206744784-fea029e9-c952-47d2-8160-76fe44878a33.jpg)

### What is the expected behaviour?

I expect something dosent let me go on this server

### How do you recreate this bug or crash?

1. i install Aliucord
2. i join discord server 
3. it do nothing :/

### Crash-log

```
i do not have logs
```

### Request Agreement

- [x] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
no logs?

**Comment by DiamondMiner88** [comment]
oh you're banned

**Comment by HardNeos** [comment]
> no logs?

i dont have logs

**Comment by HardNeos** [comment]
> oh you're banned

I never joined the server 💀

**Comment by HardNeos** [comment]
> > oh you're banned
> 
> I never see the server channels 💀
