### ISSUE TITLE
Jump links do not open in Aliucord

### ISSUE THREAD

**Issue by cyrus01337** [Aliucord/Aliucord#289]
### Discord Account

Cyrus#8315

### What happens when the bug or crash occurs?

Discord is opened and the jump link is processed there.

### What is the expected behaviour?

The jump link is processed in app, without relying on the standard Discord client.

### How do you recreate this bug or crash?

1) Create a message link (any message will do)
2) Tap it in Aliucord

You should see that it opens Discord and navigates (or tries to, Discord inconsistency) to the message's location as described from the jump link's route parameters.

### Crash-log

N/A

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by DiamondMiner88** [comment]
Change your default handler for discord links to Aliucord in your system settings
