### ISSUE TITLE
The app crashed when I opened it

### ISSUE THREAD

**Issue by kyzsuukii** [Aliucord/Aliucord#292]
### What happens when the bug or crash occurs?

I am having an issue with the app crashing when I open it. The app crashes immediately after I open it and I am unable to use it

https://user-images.githubusercontent.com/110718021/210710008-256fc2a4-4979-48e9-b2b4-17e8ac8c5583.mp4

### What is the expected behaviour?

The app should open without crashing.

### How do you recreate this bug or crash?

1. Open the app.
2. The app crashes.

### Crash-log

```
Version Name: 126.21 - Stable
Version Code: 126021

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Havoc-OS Version: '4.16'
Build fingerprint: 'xiaomi/cactus/cactus:9/PPR1.180610.011/V11.0.8.0.PCBMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-01-05 13:31:18+0800
pid: 2095, tid: 2095, name: com.aliucord  >>> com.aliucord <<<
uid: 10260
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xaeaec10c (*pc=0x9d6a77e1)
    r0  9e091134  r1  9d66fb9d  r2  aff3602d  r3  00000000
    r4  abfc0e10  r5  9e091134  r6  00000000  r7  beb6ee98
    r8  aea6b6f7  r9  aeebfaf4  r10 beb6eea0  r11 af5d5124
    ip  9d62fd1c  sp  beb6ee78  lr  aee640f3  pc  aeaec10c

backtrace:
      #00 pc 0012c10c  /apex/com.android.art/lib/libart.so!libart.so (offset 0x12b000) (art::ArtMethod::RegisterNative(void const*)+4) (BuildId: ffa6474f8f5b1ed7b68a5007cbdb3eab)
      #01 pc 00040e0e  [anon:scudo:primary]

```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
- Is the phone armv7 or armv8?
- Are you on a custom ROM?

**Comment by rushiiMachine** [comment]
Also a full log would be nice (debug level)

**Comment by kyzsuukii** [comment]
> - Is the phone armv7 or armv8?
> - Are you on a custom ROM?

yes and yes

**Comment by kyzsuukii** [comment]
> Also a full log would be nice (debug level)

how?

**Comment by rushiiMachine** [comment]
adb logcat *:D -d > logcat.txt

**Comment by Hostezza** [comment]
This also happened to me in Aliucord and installer like Failed to get data from github:
HandshakeException: Handshake error in client (OS Error:
SSLV3_ALERT_CLOSE_NOTIFY (tls_record.cc:594)

**Comment by Hostezza** [comment]
How do I fix?

**Comment by rushiiMachine** [comment]
unrelated issue, your ISP may be blocking github
don't hijack issues

**Comment by abiyphetot** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠛⢉⢉⠉⠉⠻⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⠟⠠⡰⣕⣗⣷⣧⣀⣅⠘⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠃⣠⣳⣟⣿⣿⣷⣿⡿⣜⠄⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠁⠄⣳⢷⣿⣿⣿⣿⡿⣝⠖⠄⣿⣿⣿⣿⣿
⣿⣿⣿⣿⠃⠄⢢⡹⣿⢷⣯⢿⢷⡫⣗⠍⢰⣿⣿⣿⣿⣿
⣿⣿⣿⡏⢀⢄⠤⣁⠋⠿⣗⣟⡯⡏⢎⠁⢸⣿⣿⣿⣿⣿
⣿⣿⣿⠄⢔⢕⣯⣿⣿⡲⡤⡄⡤⠄⡀⢠⣿⣿⣿⣿⣿⣿
⣿⣿⠇⠠⡳⣯⣿⣿⣾⢵⣫⢎⢎⠆⢀⣿⣿⣿⣿⣿⣿⣿
⣿⣿⠄⢨⣫⣿⣿⡿⣿⣻⢎⡗⡕⡅⢸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⠄⢜⢾⣾⣿⣿⣟⣗⢯⡪⡳⡀⢸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⠄⢸⢽⣿⣷⣿⣻⡮⡧⡳⡱⡁⢸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⡄⢨⣻⣽⣿⣟⣿⣞⣗⡽⡸⡐⢸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⡇⢀⢗⣿⣿⣿⣿⡿⣞⡵⡣⣊⢸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⡀⡣⣗⣿⣿⣿⣿⣯⡯⡺⣼⠎⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣧⠐⡵⣻⣟⣯⣿⣷⣟⣝⢞⡿⢹⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡆⢘⡺⣽⢿⣻⣿⣗⡷⣹⢩⢃⢿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣷⠄⠪⣯⣟⣿⢯⣿⣻⣜⢎⢆⠜⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡆⠄⢣⣻⣽⣿⣿⣟⣾⡮⡺⡸⠸⣿⣿⣿⣿
⣿⣿⡿⠛⠉⠁⠄⢕⡳⣽⡾⣿⢽⣯⡿⣮⢚⣅⠹⣿⣿⣿
⡿⠋⠄⠄⠄⠄⢀⠒⠝⣞⢿⡿⣿⣽⢿⡽⣧⣳⡅⠌⠻⣿
⠁⠄⠄⠄⠄⠄⠐⡐⠱⡱⣻⡻⣝⣮⣟⣿⣻...
