### ISSUE TITLE
The install button is grey and aliucord was does not installed anymore

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [Aliucord/Aliucord#293]
### What happens when the bug or crash occurs?

The install button is grey and aliucord does not install anymore

This is the picture of the bug :-
![Screenshot_20230108-211844](https://user-images.githubusercontent.com/109818645/211206298-ac57d6ee-0e9b-4cc0-968b-a38051135659.png)

### What is the expected behaviour?

This is really bad thing

### How do you recreate this bug or crash?

This not a main thing

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by neko-astolfo-uwu** [comment]
Use a vpn

**Comment by SohamRoy20Gaming** [comment]
Which VPN ?On Jan 8, 2023 9:28 PM, neko-astolfo-uwu ***@***.***> wrote:
Use a vpn

**Comment by rushiiMachine** [comment]
doesn't matter
