### ISSUE TITLE
Cant join the Aliucord Support Server

### ISSUE THREAD

**Issue by TheCoderX22** [Aliucord/Aliucord#294]
### Why get i Banner on the Support Server.

Hello! I want to join the Support Server to install Plugins and other things. I tried to join the server with my alt acc over aliucord. It doesnt work. I tried it over my main acc over original discord. But im Banned. Pla help me

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by TheCoderX22** [comment]
@rushiiMachine ?

**Comment by Vendicated** [comment]
![image](https://user-images.githubusercontent.com/45497981/212501015-08352e4a-39ff-4d6d-b44e-9d2253c76934.png)
