### ISSUE TITLE
When I open the app then it's crashed.

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [Aliucord/Aliucord#295]
### What happens when the bug or crash occurs?

When I open the app then it's shown Aliucord isn't responding.

### What is the expected behaviour?

This so bad thing.
Please quickly fix this thing, it's freaking me.

### How do you recreate this bug or crash?

This no a main question.

### Crash-log

![Screenshot_20230114-223918](https://user-images.githubusercontent.com/109818645/212526265-08cbb279-7855-4e34-8ccf-6eae51af1117.png)

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by SohamRoy20Gaming** [comment]
Please fix this early.

**Comment by rushiiMachine** [comment]
What you provided is not a crash log.
Please provide an actual log

**Comment by SohamRoy20Gaming** [comment]
But, How I Upload The Crash Log

**Comment by rushiiMachine** [comment]
**How do I provide a logcat?**

You will need:
- A computer
- ADB installed (<https://streamable.com/h0618w>)

1. Enable USB debugging in your phone's developer options
2. Run the following command in a terminal (cmd for Windows):
```sh
adb logcat -c
```
3. If you have not previously authorized adb on your phone, open it now and authorize your pc
4. Now open OpenCord and reproduce the issue
5. Run the following command now
```sh
adb logcat -d > logcat.txt
```
6. The generated logcat will be in your user home directory

**Comment by SohamRoy20Gaming** [comment]
I don't have any computer or laptop.
