### ISSUE TITLE
Forum Channel Formatting Problems

### ISSUE THREAD

**Issue by CLtheman1** [Aliucord/Aliucord#297]
### What happens when the bug or crash occurs?

The formatting(markdown) in forum channels is messed up on Aliucord.

Once, I put bold formatting in quote block and it did double bullet points. Along with that, I did an empty line in quote block, but the quote block for that line didn't render, but just showed ">".

Another post I made just broke up into a column of new lines. It's better explained in screenshots:

![Screenshot_20230124-122332](https://user-images.githubusercontent.com/42390803/214374148-aafc1809-4ca5-4896-8fd5-afc69c89f396.jpg)
![Screenshot_20230124-122638](https://user-images.githubusercontent.com/42390803/214374179-2fef7d6b-a28f-4ad5-a75d-fe5a41200f32.jpg)

### What is the expected behaviour?

The formatting should work normally, as it does in vanilla Discord.

Here are screenshots of the same posts, but in vanilla Discord:

![Screenshot_20230124-114824_Discord](https://user-images.githubusercontent.com/42390803/214376370-c2fd7ed4-a954-4e66-a43a-4082f0bfb6b0.jpg)
![Screenshot_20230124-112149_Discord](https://user-images.githubusercontent.com/42390803/214376377-757c9fa9-523a-4cce-a97a-49de40734f26.jpg)

### How do you recreate this bug or crash?

1. Get on Discord and make a forum post with a bunch of formatting. Include things like quote blocks, bold, italics, and bullet points.
2. Get on Aliucord and just look at that post.

### Crash-log

[No crash.]

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by GangsterFox** [comment]
You gotta remember that the last Discord version of kotlin was right in the middle of discord finishing up the forum channels so a lot of the stuff is just not available on the kotlin client 

Basically inhale some cope for now
