### ISSUE TITLE
Update aliucord

### ISSUE THREAD

**Issue by speedlorenzo12** [Aliucord/Aliucord#298]
### Discord Account

! speedlorenzo12#0906

### What is it that you'd like to see?

update aliucord starts to be outdated needs to be updated to the latest version to be on par with discord (162.10) i understand its a hard thing to do but its possible please do this to revive aliucord and be better

### Go into more detail...

Already do

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by nikosszzz** [comment]
Be patient for it to be completed.

**Comment by speedlorenzo12** [comment]
Thanks

**Comment by rushiiMachine** [comment]
> The release date is 30 days from now to the power of how many people have asked about it
