### ISSUE TITLE
App glitch 

### ISSUE THREAD

**Issue by AHIRROHIT** [Aliucord/Aliucord#299]
### Discord Account

!      RNP TECH GAMING#0921

### What happens when the bug or crash occurs?

I can't Have Install Button on Aliucord downloader apk

Pls fix this

### What is the expected behaviour?

↑

### How do you recreate this bug or crash?

Idk

### Crash-log

```
Replace this text with your crash-log.
```
Not crasing

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
use a vpn
