### ISSUE TITLE
Can't join Aliucord Server

### ISSUE THREAD

**Issue by Upsidedowncake81363** [Aliucord/Aliucord#302]
### Discord Account

Upsidedowncake#9789

### What happens when the bug or crash occurs?

![Screenshot_20230224-111126](https://user-images.githubusercontent.com/126227095/221101201-5102205a-f0cc-4659-a3aa-42d607415299.png)
I cannot join Aliucord server
It become a problem for me

### What is the expected behaviour?

Whenever I try to join Aliucord server it ignores to join and now it shows that the link is expired. Is it expired idk please check
I can join other server not this 

### How do you recreate this bug or crash?

No it is a bug

### Crash-log

No crash log

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
link in the readme (discord button) does indeed work
if it still doesnt for you then you're banned

**Comment by Upsidedowncake81363** [comment]
I think i am banned and i don't know why
