### ISSUE TITLE
Support for Discord's Stable Release 166 and above

### ISSUE THREAD

**Issue by Wlz-23** [Aliucord/Aliucord#304]
### What is it that you'd like to see?

Supporting Aliucrod for newer version of the Discord app so that we are able to utilise new features that are added natively on discord.

### Go into more detail...

The February 20 update on discord added some really lovely QoL changes not present on Aliucord such as the "Multiple Images, One Message" feature and "Send messages silently". While I usually do pay attention to new discord updates these 2 features did however make me pause for a second. After a little bit of digging, I found out that Aliucord runs on Version 126.1 while the current version is above 160. 

Seeing that the 126.1 version was released in June 2022 there are also probably some security stuff that have been patched and whatnot but I think that someone should start considering moving to a newer version.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by GangsterFox** [comment]
Hi! If you could check the announcement channel, the team is working on a new version. Sorry it's taking such a long time.
(Psst... you can check out the AliuRN [thread](https://discord.com/channels/811255666990907402/1029150345487728750) in offtopic if you want really want to see the progress, but be aware that its prone to have issues sometimes)
