### ISSUE TITLE
Sorry but this isnt a bug report

### ISSUE THREAD

**Issue by MechLordBR** [Aliucord/Aliucord#305]
### Tell us all about it.

Im looking on how to join the discord server.
I've downloaded the app and tried joining the server for support and plugins but i cant join.
How do i join?

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by GangsterFox** [comment]
Please do not use Github Issues to ask for server support.
Please try joining again as your account was under 2 days old.

**Comment by MechLordBR** [comment]
Ok thank you
