### ISSUE TITLE
aliucord 146.8 kept on crashing, could even get to login page |:{

### ISSUE THREAD

**Issue by idontveapc** [Aliucord/Aliucord#334]
### Discord Account

umm hmm, why this? i said it couldn't, CRASHED before it mf-ing.

### What happens when the bug or crash occurs?

ya mom gets fucked.

### What is the expected behaviour?

get ya mom unfucked.

### How do you recreate this bug or crash?

ya mama do it by haself.

### Crash-log

```
Replace this text with your crash-log.
```
i said couldn't, it won't let me get in, it crashes each and every time, ever and ever. crashlog isn't even made or saved in device/storage/emulated/0/aliucord.

serious now

it's armv7 apk & i tried both default hermes and libc++, nothing happened btw, it's crashing.

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
1. wrong repo
2. stop using manager if you don't know what you're doing

aliurn is not ready yet

**Comment by idontveapc** [comment]
> 2. stop using manager if you don't know what you're doing

***why** should i?* on aliucordrn repo no one is reporting issues, they are doing on discord.

so i did here.

rather making clear where should i report, just fix it!
