### ISSUE TITLE
aliucord uses google analytics and stores them in system folders everytime you open

### ISSUE THREAD

**Issue by chiron853** [Aliucord/Aliucord#336]
### What happens when the bug or crash occurs?

when i open the app

### What is the expected behaviour?

i expect aliucord to block any analytics and not store them anywhere 

### How do you recreate this bug or crash?

open aliucord then analytics file is created at  data_mirror/data_ce/null/0/com.aliucord/files and it collects device information 
![image](https://user-images.githubusercontent.com/68013299/231563583-20cddc5c-bad4-4ebf-bff1-2ab2329da4a8.png)
![image](https://user-images.githubusercontent.com/68013299/231563615-0027be8a-1b46-4d59-9c56-38dd11649bdf.png)

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by dxcvvxd** [comment]
/data/* folders arent exactly system ones and im pretty sure that data doesnt go anywhere, you can check it with `netstat` command if you have root and some sort of busybox installed

**Comment by zt64** [comment]
None of the data is sent to Discord or any other tracking places. Aliucord just disables the methods that perform the network function portion

**Comment by rushiiMachine** [comment]
> None of the data is sent to Discord or any other tracking places. 

If there is any evidence to support that this happens feel free to reopen

**Comment by chiron853** [comment]
> /data/* folders arent exactly system ones and im pretty sure that this data doesnt go anywhere, you can check it with `netstat` command if you have root and some sort of busybox installed

but i still want to stop aliucord from collecting data automaticly

**Comment by rushiiMachine** [comment]
> and it goes to google api 

As long as you don't have google play services then to my knowledge no data is sent
Unfortunately if you want notifications you need gcm
