### ISSUE TITLE
Problems when building with gradle (I can't find an important line to modify)

### ISSUE THREAD

**Issue by kilam8900** [Aliucord/Aliucord#340]
### Tell us all about it.

First, hoping you're having a good day, I was trying to port Aliucord for discord 174.13. After I manually patched the AndroidManisfest (the patch is deprecated from far) I changed the targetSDK and blabla after that and I fell on a very easy error to fix, fragment of my log : 

`A problem occurred configuring root project 'Aliucord'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.js6pak:jadb:fix-modified-time-SNAPSHOT.
     Required by:
         project : > com.github.Aliucord:gradle:main-SNAPSHOT:cb333051d9-1 > com.github.Aliucord.gradle:gradle:main-SNAPSHOT:cb333051d9-1
      > Could not resolve com.github.js6pak:jadb:fix-modified-time-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/js6pak/jadb/fix-modified-time-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://jitpack.io/com/github/js6pak/jadb/fix-modified-time-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
`

I know to fix it, change from [https://jitpack.io/com/github/js6pak/jadb/fix-modified-time-SNAPSHOT/maven-metadata.xml to https://jitpack.io/com/github/vidstige/jadb/1.2.1/maven-metadata.xml or from the old dependecy to something the new repo. But I don't know where is it in what file, I searched for like 30 min on the repo but I didn't find it. So I'm here to please you ask where did github/js6pak/jadb go?

If you tell me where is it, I can possibly try to make a stable thing for the 174.13 (or not tho, I'am not a pro)

Enjoy your day

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
1. This project is incompatible with >discord 126.21 (refer to Aliucord/AliucordRN)
2. I am working on moving away from jitpack

**Comment by kilam8900** [comment]
My bad, I was thinking that something had change with discord but I didn't know it was a rebuild.
This aliucord repo is going to be deprecated? And the AliucordRN can at least run?

**Comment by rushiiMachine** [comment]
> This aliucord repo is going to be deprecated? And the AliucordRN can at least run?

no and no

**Comment by kilam8900** [comment]
Okay, Thank you very much for your help
