### ISSUE TITLE
Update to 175.16 anytime soon?

### ISSUE THREAD

**Issue by NightKido** [Aliucord/Aliucord#345]
### Tell us all about it.

The 8mb limit is gone, now it's 25mb. Aliucord must have an update by now increasing that size barrier. The old theme can stay, I personally like it.

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
no, and we already updated the limit to 25mb excluding dms

**Comment by NightKido** [comment]
Wow great. I can't wait to have absolutely nothing new for endless months

**Comment by SykNeo** [comment]
https://github.com/vendetta-mod/VendettaManager
