### ISSUE TITLE
Plugins for everyone (DC server)

### ISSUE THREAD

**Issue by zeex4** [Aliucord/Aliucord#356]
### What is it that you'd like to see?

By default every new discord user is kicked/banned from server based on some criteria when trying to join. 
While looking for [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) Discord clients I've came upon this project _which could_ create much better experience (ex. GSF/FireBase/"X" tracking company blocking) as well as plugin system like in [BetterDiscord](https://github.com/BetterDiscord/BetterDiscord). 
Whats the point of kicking/banning/restricting new accounts to the point that they **can't access major project feature** (which is the plugin system)?

You can implement way better bot protection or make publicly accessible git repo instead of "Join to access core features" approach which sounds like a business model.

To clarify: My account has been created at the same time of client installation & I've never been banned on any discord server before.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by mantikafasi** [comment]
new accounts get atomaticly banned,just join with your main account

**Comment by Vendicated** [comment]
> make publicly accessible git repo

just search for Aliucord on github

> Whats the point of kicking/banning/restricting new accounts

your account nerds to be incredibly new to even get banned, iirc it's 1 day minimum age. noone installs discord and immediately installs mods, so anyone with that new of an account is definitely an alt. just use your main or wait a few days

**Comment by Vendicated** [comment]
> GSF/FireBase/"X" tracking company blocking

also on an unrelated note, neither GSF nor FireBase are actually blocked as they're crucial for some basic features like notifications to work. Only the tracking aspects are. if you don't want these to run, simply do not have Google play services installed on your system, discord will work anyway (albeit without notifications)
