### ISSUE TITLE
Obscure crash with slash commands 

### ISSUE THREAD

**Issue by someunknowndude** [Aliucord/Aliucord#357]
### Discord Account

quirky anime boy#5506

### What happens when the bug or crash occurs?

You can crash the application by putting a slash command like /me message:test into the message bar and then adding 1 backslash right after the slash command and then placing one in front of the "message" argument. Typing a backslash before the argument without having placed one after the command will move the backslash into the "message" field

### What is the expected behaviour?

In the latest Version of discord when adding a backslash in this Position it will escape the message argument field. Having one right after the command doesnt do anything.

### How do you recreate this bug or crash?

1. Enter a built-in command into the text field
2. Fill out the message argument with some text
3. Move the text cursor right after the actual slash command but not the space
4. Type a \
5. Move the cursor right in front of the message field
6. Type a \
7. The app should now crash (forced to close)

tested on a galaxy s9 on Android 10

### Crash-log

No crash log gets created by this crash

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
simply... don't do that?

**Comment by rushiiMachine** [comment]
ig this is a bug but not really our bug
yell at discord to fix their native app (it wont happen)
