### ISSUE TITLE
Make a spoiler image toggle

### ISSUE THREAD

**Issue by JumpCatGD** [Aliucord/Aliucord#361]
### Discord Account

JumpCat#1945

### What is it that you'd like to see?

I want to see a spoiler toggle when you a send an image when i tap on the miniature of it. (Sorry for bad english :) )

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
> **Clicking the attachment preview when uploading an attachment removes the attachment instead of opening the Modal where you can spoiler the image**

Install the Experiments plugin then go to Discord Settings > Developer Options and set the Experiment "Attachments Bottom Sheet" to Bucket 1 and restart Discord

Plugin: <https://discord.com/channels/811255666990907402/811275162715553823/835554229484519484>
