### ISSUE TITLE
I can't join the Aliucord server

### ISSUE THREAD

**Issue by lovelyMoonar** [Aliucord/Aliucord#367]
### Tell us all about it.

I tried to join aliucord serve trough the Aliucord, Discord and web discord. I get to the friend list when I try to join on apps and an error message on web browser. 
![Uploading Screenshot_20230702-174651.png…]()
My account is about a month old and doesn't have phone verification. 
![Screenshot_20230702-175320](https://github.com/Aliucord/Aliucord/assets/98496724/72e5382d-192f-42d3-8ddc-1bf7f63fad9a)

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by lovelyMoonar** [comment]
Looks like my first photo upload is not loading, I'll send again 
![Uploading Screenshot_20230702-174651.png…]()

**Comment by Vendicated** [comment]
you were banned due to account age. Unbanned
