### ISSUE TITLE
Add in-aliucord message link

### ISSUE THREAD

**Issue by JumpCatGD** [Aliucord/Aliucord#368]
### What is it that you'd like to see?

Now all msg links open in default discord. Add link which can transfer you to message in aliucord. Type of link: discord.com/channels/...

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Canny1913** [comment]
just enable "open links by default" in app settings

**Comment by rushiiMachine** [comment]
^ change your default discord link handler in system settings

**Comment by JumpCatGD** [comment]
> ^ change your default discord link handler in system settings

I am cant find this

**Comment by Quinxxxx** [comment]
go to your homescreen > hold discord > click apl info button > find where it mentions allow opening links and disable/turn off
go back go homescreen and repeat for aliucord but instead turn on allow opening links and select all links if it lets u
![Screenshot_2023-07-20-09-33-51-75_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Aliucord/Aliucord/assets/88912716/2b1eac71-6061-407a-96a9-3a96ba997c4d)

**Comment by JumpCatGD** [comment]
> go to your homescreen > hold discord > click app info button > find where it mentions allow opening links and disable/turn off go back go homescreen and repeat for aliucord but instead turn on allow opening links and select all links if it lets u ![Screenshot_2023-07-20-09-33-51-75_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/88912716/254824563-2b1eac71-6061-407a-96a9-3a96ba997c4d.jpg)

thx
