### ISSUE TITLE
Icon theming support with material you

### ISSUE THREAD

**Issue by Enderteck** [Aliucord/Aliucord#371]
### Discord Account

Enderteck#0172

### What is it that you'd like to see?

I'd love for the icon to be, like Twitter, Google and Whatsapp themed with the material you theme which makes the app not stick out of my homescreen.

Thx in advance ♥️

### Go into more detail...

It could just be a option in aliucord installer ?

![Screenshot_20230723_225449_One UI Home](https://github.com/Aliucord/Aliucord/assets/123917079/7d988fce-2bac-4e8f-b90c-ae860bc97df8)

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
https://github.com/Aliucord/AliucordManager/issues/37
