### ISSUE TITLE
[Feature Request] Add a button to open aliucord's plugin folder

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/Aliucord#38]
Since Aliucord is getting more and more popular, as the store isn't coming, it would be better to add a 3-dots menu in the plugin page, where it shows an option to open Aliucord's plugin folder

**Comment by Vendicated** [comment]
Implemented in https://github.com/Aliucord/Aliucord/commit/cdcabae5809e4da028816021cd9a3fd7d3d7b73b
