### ISSUE TITLE
Message encryption for client users who use the plugins

### ISSUE THREAD

**Issue by zerobun** [Aliucord/Aliucord#384]
### What is it that you'd like to see?

A plugin which allows 2 users to communicate is encrypted messages which are decrypted if the other user has the same plugin.

### Go into more detail...

I think this is needed because you got discord and 38% of it is owned by tencent and that's a Chinese company with massive privecy issue and is also owned 50% by the Chinese government. They also have an obligation all and any info if the gov requests
Discord also mentions in their policy that they might give our data to their owners for ads purposes, which clearly raises privecy red flags.

So having a method which will literally create encrypted messages which can only decrypted by another user of he plugin would be nice as they won't get any real message data.
Ofc it has its limitations such as a person not using the plugin what would they see, well we can simply make it a client feature or jus use it as a DM nly feature so it's clear to know who has the plugin or not and is able to see the messages properly and not see randomly numbers and letters. 

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
plugin already exists + wrong repo

**Comment by zerobun** [comment]
> plugin already exists + wrong repo

Can you tell me the name for it?

**Comment by rushiiMachine** [comment]
oh i was wrong it was never finished
plugin request exists: https://github.com/Aliucord/plugin-requests/issues/33
