### ISSUE TITLE
Installer not showing install option 

### ISSUE THREAD

**Issue by killerlearner** [Aliucord/Aliucord#393]
### Tell us all about it.

I was using aliucord and it started crashing so I uninstalled it and try installing new using installer app. But it isn't showing install option.

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
go to the support discord channel

**Comment by killerlearner** [comment]
How can I go to discord channel when it's not opening.
I don't use official discord
