### ISSUE TITLE
Please update to a newer discord version. 

### ISSUE THREAD

**Issue by SudoTheHacker** [Aliucord/Aliucord#395]
### Discord Account

munantuwan

### What is it that you'd like to see?

Voice recordings are unsupported and it's very annoying.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
> **Update on Aliucord status**
We decided to keep all development on the good old 126.21 version of Discord, which is the last version of Discord that doesn't use React Native framework. It may lack of new features that Discord added in the past year, but we should be able to keep existing functionality and to add some new features.
> Also we cancelled Aliucord React Native project (which was Aliucord for newer Discord versions), because most of our developers just disliked working and using Discord React Native (its performance is really poor and is full of bugs, there are many reasons to just not like it). If you still want to use new Discord with mods, the best choice is Vendetta (made by different team, unaffiliated).
