### ISSUE TITLE
Aliucord No Longer Opens After Most Recent Update

### ISSUE THREAD

**Issue by UnverifiedHuman** [Aliucord/Aliucord#396]
### What happens when the bug or crash occurs?

Aliucord can no longer be opened.

### What is the expected behaviour?

Aliucord opening and otherwise functioning normally.

### How do you recreate this bug or crash?

I updated Aliucord to the latest version. Now, when I try to update it again, the installer gets stuck. See attached file.
![Screenshot_2023-10-21_15-22-49](https://github.com/Aliucord/Aliucord/assets/148658077/ce9f81af-75d2-478c-b0e0-1874ce8a12c7)

**Comment by rushiiMachine** [comment]
delete installer storage and try again
this is not a support channel, visit the discord if you have any more issues
