### ISSUE TITLE
why??

### ISSUE THREAD

**Issue by YashSoPro** [Aliucord/Aliucord#397]
### Discord Account

sablenotfound

### What happens when the bug or crash occurs?

this is not a issue and might be stupid for you but because creating a issue for being unbanned is 
unusual and stupid i know but your admins banned me for no reason i didn't abused or trash talked they banned me for reason being child how was that being child
please take actions against it and unban me

if i have also done something i apologise for it!👍

### What is the expected behaviour?

idk 

### How do you recreate this bug or crash?

idk

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
![image](https://github.com/Aliucord/Aliucord/assets/33725716/30417709-e889-4116-90c1-422b4ff8b818)
![image](https://github.com/Aliucord/Aliucord/assets/33725716/9026fe8a-c379-434d-816c-060443aae8d6)
