### ISSUE TITLE
New Twemoji emojis

### ISSUE THREAD

**Issue by 5h3i1ah** [Aliucord/Aliucord#406]
### Discord Account

5h3i1ah

### What is it that you'd like to see?

The fork of Twemoji that Discord uses got an update, so Discord now officially supports yet more emojis. I would greatly appreciate if these were added to Aliucord! https://github.com/jdecked/twemoji

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Juby210** [comment]
Already a plugin. [NewEmojis](https://github.com/Juby210/Aliucord-plugins#newemojis)
