### ISSUE TITLE
Make discord pronoun appear in chat

### ISSUE THREAD

**Issue by Eve9181** [Aliucord/Aliucord#407]
### What is it that you'd like to see?

it would be nice to have an option to make the discord pronouns visible in chat like pronoun db has

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
not possible without abusing the api; pronouns aren't sent with the user object on messages

**Comment by Vendicated** [comment]
to explain a bit better:

pronouns aren't sent alongside the message data. discord only sends them when you open the person's profile. so to display pronouns in chat, Aliucord would need to fetch the profile of every person in chat, which would be api spam / abuse and likely get you rate limited

**Comment by Eve9181** [comment]
oh alright
i got a question tho,
does that mean vencord's pronoun db plug-in is abusing the api cause it's possible in vencord
or it's not possible in aliucord because it's an older version?

**Comment by Vendicated** [comment]
vencord's pronoun plugin only displays pronouns in chat if they're already fetched, meaning 99% of people's pronouns won't show in chat until you open their profile

**Comment by Eve9181** [comment]
oh okay
