### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by aviadmini** [Aliucord/Aliucord#408]
### What is it that you'd like to see?

Having the app released on F-Droid store would be easier for users to download and potentially get more reach. 

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Juby210** [comment]
You can't publish closed source apps on F-Droid. Open source modification to closed source app still uses closed source code.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Aliucord/Aliucord/issues/408#issuecomment-1859185871

@Juby210, that's solely for the 1st-party repository. You can host your own.

**Comment by Ushie** [comment]
By hosting our own, the motivation of more reach no longer applies.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Aliucord/Aliucord/issues/408#issuecomment-1987118581

@Ushie, https://github.com/Droid-ify/client/blob/6a06c17e0ae1245008a242481a6b809948ab611e/core/domain/src/main/kotlin/com/looker/core/domain/Repository.kt#L101-L387 should demonstrate otherwise - popular alternative clients frequently include useful 3rd-party repositories.

**Comment by rushiiMachine** [comment]
Droidify is a 3rd party client, the "more reach" is negligible. There's no guarantee that droidify or any other 3rd party client will include our repository.
