### ISSUE TITLE
I can't use slash commands

### ISSUE THREAD

**Issue by deepak1234123** [Aliucord/Aliucord#414]
### Discord Account

its_deepu

### What happens when the bug or crash occurs?

I can't use bot _**slash commands**_ on any server please help me

### What is the expected behaviour?

Idk

### How do you recreate this bug or crash?

Idk

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
#412
