### ISSUE TITLE
GIF Stickers not showing up.

### ISSUE THREAD

**Issue by Apethesis** [Aliucord/Aliucord#419]
### Discord Account

@compec

### What happens when the bug or crash occurs?

The bug happens supposedly only with new stickers, which just have the placeholder icon instead of whatever the sticker is. When sent by another person the sticker shows up as the most recently seen/loaded one.
![Screenshot_20240129_160517](https://github.com/Aliucord/Aliucord/assets/86126617/d8c23e7a-7422-408d-a0ac-76058a0c2757)

### What is the expected behaviour?

I expect to be able to see the sticker and use it as normal.

### How do you recreate this bug or crash?

1. Make a new GIF sticker in a server (on desktop)
2. Attempt to use it or view it on mobile
3. Profit

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Apethesis** [comment]
Also for some reason (just noticed), default discord server icons dont show up. Might make a separate issue for that later...

**Comment by Delphox** [comment]
Some GIF stickers are still not loading (or showing as the last sticker you saw) but whenever I try to reupload them in a test server they do load, so there might still be something up with them. Here's a couple example from public servers:

Example from Aliuwucord server: https://discord.com/channels/811255666990907402/811255667469582420/1184949465363251230

Example from Super Animal Royale server: https://discord.com/channels/413200888010637313/413200888010637317/1204322328507449404 

@Juby210

**Comment by Juby210** [comment]
should be fixed with next update

**Comment by Delphox** [comment]
GIF stickers recently stopped animating, you can test by yourself by clearing the cache first. They still animate on commit fac7625da89593df9e68617bf4527a0a9dcc82b5 before the StickerPartial fix, so I did a quick test and reintroducing the fallback to GIF for both Sticker and StickerPartial seems to fix it.

This might have to do with Discord starting to use animated webp on stock recently, which isn't supported on Aliucord.
