### ISSUE TITLE
One UI 6.0 update breaking Aliucord

### ISSUE THREAD

**Issue by BabyBoy666** [Aliucord/Aliucord#421]
### Discord Account

AnActualBaby#6853

### What happens when the bug or crash occurs?

Aliucord appears as an outdated version of stock discord, all features, including plugin downloader and previously installed plugins appear to be missing. According to another user, reinstalling after this results in a completely bricked installation(I have not attempted cause I don't wanna break mine :p)

### What is the expected behaviour?

Aliucord to launch as modded not stock

### How do you recreate this bug or crash?

1. Install the Samsung One UI 6.0 update
2. Launch Aliucord 

### Crash-log

This bug appears to not result in any crash logs, the newest in the folder was from Dec 2023

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by BabyBoy666** [comment]
Nvm, found a fix!

**Comment by ffoxD** [comment]
> Nvm, found a fix!

hi, could you like, tell what the fix was? it would help anyone else having the same issue, and the developers fixing the actual problem itself

**Comment by BabyBoy666** [comment]
> > Nvm, found a fix!
> 
> hi, could you like, tell what the fix was? it would help anyone else having the same issue, and the developers fixing the actual problem itself

Yeah, np! I essentially had to a completely fresh install, deleting all Aliucord folders, including the ones related to the installer, and then reinstall from there after that full wipe
