### ISSUE TITLE
[feature request] making a custom nickname to someone

### ISSUE THREAD

**Issue by tuleo1** [Aliucord/Aliucord#43]
so basically it would be pretty cool to make a nickname to a specific person.
so for example if I have a friend that in dms or server his name is "kairo" I could use this plugin and change his name to let's say "pie" so in the server chat or in dms it'll show "pie" instead of "kairo"

**Comment by Juby210** [comment]
use https://github.com/Aliucord/plugin-requests/issues for plugin requests
