### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by rin-ikagari** [Aliucord/Aliucord#430]
### What happens when the bug or crash occurs?

When I try to open Aluicord, the app closes without any warning, only warning is sometimes giving me the prompt "Aluicord keeps crashing", the app wasn't updated, neither there's a difference when I updated it, nothing prior was done before it crashed

### What is the expected behaviour?

To have the app opening

### How do you recreate this bug or crash?

Open the app, it'll close

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
please go to the #support channel in the Discord
