### ISSUE TITLE
Aliucord stuck on connecting

### ISSUE THREAD

**Issue by InsertSnowHere** [Aliucord/Aliucord#437]
### Discord Account

Insertsnowhere

### What happens when the bug or crash occurs?

Aliucord worked fine for months until now, it just happened without no reason but aliucord is stuck on connecting, even if I reinstalled everything it was still stuck in it, discord and every other app works fine so it can't be my wifi connection, and what make things weirder is that I still get notifications from my friends even though it's not working

### What is the expected behaviour?

Aliucord isn't supposed to be stuck on connecting for hours

### How do you recreate this bug or crash?

No known cause or ways to recreate this, it randomly just happened and forever stuck in "connecting...." despite reinstalling aliucord and even aliucord installer

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
#436
