### ISSUE TITLE
Support the React Client.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Aliucord/Aliucord#440]
### Discord Account

https://linksta.cc/going/380957121?https://discord.com/users/798720532848705576

### What is it that you'd like to see?

The current Kotlin client is notably faster on my Fairphone 4, but lacks many features which I expect — most are explained in https://discord.com/blog/android-react-native-framework-update. I haven't noticed anything in https://github.com/Aliucord/Aliucord/blob/ecbb1fa22a4025d7984026dedca38223de314722/README.md#aliucord specifying that the goal of https://github.com/Aliucord/Aliucord.git is solely to improve the Kotlin version.

### Go into more detail...

As an example, https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-221-16-stable-release/discord-talk-chat-hang-out-221-16-stable-android-apk-download/download/?forcebaseapk=true#file or above.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by jedenastka** [comment]
> I haven't noticed anything in [README] specifying that the goal of [Aliucord] is solely to improve the Kotlin version.

Well, it is. Supporting RN would require making a completely new mod.

This will never happen. While there was an attempt in the past, the devs lost interest.
