### ISSUE TITLE
Aliucord installer stuck at installing

### ISSUE THREAD

**Issue by Ryunoshi-source** [Aliucord/Aliucord#441]
### Discord Account

younes_samatta

### What happens when the bug or crash occurs?

It gets stuck on installing and does nothing afterwards 
![Screenshot_20240321_150401](https://github.com/Aliucord/Aliucord/assets/96547485/a4a31386-bd21-4b5b-96d8-5a7d9429162e)

### What is the expected behaviour?

I can't install Aliucord using the installer

### How do you recreate this bug or crash?

1. Install Aliucord installer
2. Press install 
3. Select download

### Crash-log

Checking cached apk..
Downloading discord apk..
Done
Downloading Injector.dex..
Done
Downloading patched AndroidManifest.xml..
Done
Copying original apk (/data/user/0/com.aliucord.installer/cache/discord.apk)
java.nio.file.NoSuchFileException: /data/user/0/com.aliucord.installer/cache/discord.apk
   at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
   at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:259)
   at java.nio.file.Files.copy(Files.java:1274)
   at com.aliucord.installer.Utils.copyFile(Utils.java:69)
   at com.aliucord.installer.MainActivity.lambda$onCreate$6$MainActivity(MainActivity.java:125)
   at com.aliucord.installer.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:10)
   at java.lang.Thread.run(Thread.java:1012)

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
Grant manage storage permissions and try again

**Comment by YounesSamatta** [comment]
> Grant manage storage permissions and try again

Actually i managed to fix it, the problem occurs when you don't have enough storage space left
So make sure you have atleast 2-3gb free before installing

**Comment by Ryunoshi-source** [comment]
> Grant manage storage permissions and try again

 i managed to fix it, the problem occurs when you don't have enough storage space left.
So make sure you have atleast 2-3gb free before installing
