### ISSUE TITLE
TOS and Policies popup persists despite clicking "Got It"

### ISSUE THREAD

**Issue by nayvin2** [Aliucord/Aliucord#443]
### What happens when the bug or crash occurs?

Upon Aliucord boot, theres a TOS and policies popup and doesn't go away upon clicking "Got It" button.
![Screenshot_20240415-145939](https://github.com/Aliucord/Aliucord/assets/167141198/11d082e5-a3fe-4153-b3b3-6a63209b0393)
Cycling the Logout, Phone Restart, or install do not change the outcome.

### What is the expected behaviour?

Expected behavior: The policy content blocker screen never appears. OR The policy content blocker goes away upon clicking the "Got It" Button.

### How do you recreate this bug or crash?

1. Login Per usual.
2. Click the "Got It" Button
3. Click the "Got It" Button
4. Click the "Got It" Button
Ad Infinitum 

### Crash-log

N/A

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by nayvin2** [comment]
It's not infinitely many, but its a lot of the screens Ive found. Clicking through about 40~ then it let me into aliucord.

**Comment by rushiiMachine** [comment]
When was the last time you logged into discord...

**Comment by mikwee** [comment]
I just woke up and found this bug. Last time I logged into Discord was… if you're talking about the actual logins e

**Comment by rushiiMachine** [comment]
I'm just gonna close this because it's a one off thing and not really worth the effort fixing
