### ISSUE TITLE
My microphone does not work in VC

### ISSUE THREAD

**Issue by mikwee** [Aliucord/Aliucord#446]
### Discord Account

mikwee@0000

### What happens when the bug or crash occurs?

This happens whenever I join VC and try to turn on my mic and speak. It shows that my mic is on, but I am not heard, and then I get this error: `We couldn't enable Krisp due to an error. Give it another go and try again`. It doesn't reappear if I turn on my mic and speak again.

### What is the expected behaviour?

I expected Aliucord to record me instantly and allow me to voice chat.

### How do you recreate this bug or crash?

1. Join a voice chat
2. Turn on your microphone

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by mikwee** [comment]
Update: VC works when you turn all of Krisp off. Still, it's worth to fix the issues with Krisp.

**Comment by rushiiMachine** [comment]
We can't fix any alleged issues with krisp
