### ISSUE TITLE
Update Base Version

### ISSUE THREAD

**Issue by Lucas-V-L** [Aliucord/Aliucord#448]
### What is it that you'd like to see?

The current Discord version which Aliucord builds upon is severely outdated (by multiple years) and lacks a lot of the features a newer version would have. (polls, reply highlighting, and improved images layout come to mind). Is there a timeline to update the base supported client to something a bit more recent?

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
https://discord.com/channels/811255666990907402/811257821378904064/1104505325173883062
