### ISSUE TITLE
Package conflicts with existing package

### ISSUE THREAD

**Issue by Crecheer** [Aliucord/Aliucord#449]
### What happens when the bug or crash occurs?

I cant seem to install aliucord on my pixel 6a, but on every other device i can. Android just gives an error saying "App not installed as package conflicts with an existing package". I have tried to uninstall the Aliucord Installer and Discord, still doesn't work.
![Screenshot_20240501-095028](https://github.com/Aliucord/Aliucord/assets/109557492/4e145d00-54a6-475f-8bd3-57626a1d92ac)

### What is the expected behaviour?

Aliucord installs without an error

### How do you recreate this bug or crash?

1. Get the Aliucord apk
2. Try to install it

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
Please use the discord for support.
This is not a bug
