### ISSUE TITLE
crashes when attempting to open

### ISSUE THREAD

**Issue by hellohappya** [Aliucord/Aliucord#450]
### What happens when the bug or crash occurs?

i updated the app because it was being buggy and now i?? cant open it?? i reinstalled it and its still refusing to open. my phone asked me to clear the apps cache and it still wouldnt open

### What is the expected behaviour?

i expect aliucord to open

### How do you recreate this bug or crash?

1. update the app
2. app crashes

### Crash-log

there wasnt even an error screen

### Request Agreement

- [x] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
no crashlog

please go to the support channel for support
