### ISSUE TITLE
Toggleable Core Plugins

### ISSUE THREAD

**Issue by notinthegarbage** [Aliucord/Aliucord#453]
### What is it that you'd like to see?

Aliucord client should allow users to toggle core plugin functionality.

### Go into more detail...

All core plugins should include a toggle that allows users to enable/disable plugins that they view as bloat. If core plugin is a backport of a key discord feature or a bug fix user should be warned before plugin is disabled (on click). 

I believe this is especially important for the following:

1. Badges
The badges plugin is not a bug fix or a back port of a discord feature. (I personally see it as bloat and not needed for my use case.)
2. SupportWarn
Another example of a plugin that isn't fixing a bug or backporting a discord feature. Only useful for the Aliucord server alone and is not used anywhere else. Can be fully replaced by native discord member onboarding service when joining the server. Should be fully removed but a toggle would alleviate this.
3. TokenLogin
This is a convenience feature for most users. Should have a toggle to turn off if you don't ever need to use the service.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by notinthegarbage** [comment]
Making this comment to add supporting evidence for a toggle on at certain "core" plugins.

Badges is my main contender. After auditing (with my garbage ability to read code), I can conclude that Badges makes way too many network requests to pull from their database to get their donor/contributor list. There is no need to make a request to their website anytime someone opens a user profile or discord server. I'd be more okay with it if it was hardcoded into app or was stored on github but it isn't. The Aliucord server id itself isn't dynamic so, there isn't a need to send network requests to see if its on a database of "badge applicable servers". With users all you need to do is use the MEMBER LIST on Aliucord discord to see who is staff/donor/contributor. There is no need to send information of what user profiles and servers I'm viewing to query a database from aliucord that has nothing to do with a core discord fearture.

**Comment by OmegaSunkey** [comment]
Core plugins are core for a reason. The only useless and cosmetic one is badges, since its a perk for Aliucord Donors and Contributors. The Aliucord server is open source anyway. Hard-coding implies making a useless update to Aliucord core just to change a badge everytime someone donates or manually changing contributors.

**Comment by Juby210** [comment]
There's a todo comment in badges core plugin to make it a single request on Aliucord open with api url to get all badges, but I don't have time to rewrite it.

**Comment by notinthegarbage** [comment]
I personally still don't want to have the application making api calls to your servers. I'm all for having a list of contributors however, make it a channel on your support server, a role on your support server, or have an updated list each time the application is updated. Still should be toggleable since I (personally) like a pretty vanilla experience to my apps. I imagine others would agree to an extent as well.

**Comment by rushiiMachine** [comment]
done
