### ISSUE TITLE
aliucord dosnt open

### ISSUE THREAD

**Issue by savvacorgi** [Aliucord/Aliucord#458]
### Discord Account

savvacorgi

### What happens when the bug or crash occurs?

when open

### What is the expected behaviour?

open login page

### How do you recreate this bug or crash?

1 Install aliucord
2 Open aliucord

### Crash-log

idk where
![Screenshot_20240625-120712](https://github.com/Aliucord/Aliucord/assets/143608608/79c54706-8804-4faa-812e-4cec440a0456)

### Request Agreement

- [x] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
go to the support channel
