### ISSUE TITLE
Plugins get deleted when i open the app

### ISSUE THREAD

**Issue by MouseyRain98972** [Aliucord/Aliucord#460]
### Discord Account

teamunstopable668

### What happens when the bug or crash occurs?

I can't use the plugins

### What is the expected behaviour?

I expect it to show the plugins, but it prevents me from using them

### How do you recreate this bug or crash?

Put plugins into the plugins folder, open the app, go to Settings, then press on plugins, then go to the file manager, and the plugins are gone!

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
Not loading is different than "deleted". They were just not loading, because Aliucord was broken on Android 14 QPR3.

Fixed in Installer https://github.com/Aliucord/Aliucord/releases/tag/1.2.0 which includes 0e6c2a266545f4956aba3c37c445de27bd6ccce2
