### ISSUE TITLE
Froze on launch on discord logo

### ISSUE THREAD

**Issue by Crystalwarrior** [Aliucord/Aliucord#461]
### What happens when the bug or crash occurs?

Installed on HUAWEI nova 10 SE, freezes at discord logo

### What is the expected behaviour?

It launches

### How do you recreate this bug or crash?

1. Install on HUAWEI nova 10 SE
2. Watch it not launch

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [x] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
go to the support channel
