### ISSUE TITLE
Android 15 Beta 4

### ISSUE THREAD

**Issue by NeytirX** [Aliucord/Aliucord#465]
### What happens when the bug or crash occurs?

Steps to reproduce:
1. Update to Android 15 Beta 4 
2. Launch Bunny (Stable, Beta, Alpha) (Non-root) 
3. It doesn't work anymore TwT

Seems to be common to other modded launchers however.

### What is the expected behaviour?

It should allow crack to work, it doesn't even show modded options

### How do you recreate this bug or crash?

Steps to reproduce:
1. Update to Android 15 Beta 4 
2. Launch Bunny (Stable, Beta, Alpha) (Non-root) 
3. No modded options settings

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
Have you noticed this is https://github.com/Aliucord/Aliucord ? Aliucord is not related to Bunny.

**Comment by NeytirX** [comment]
> Have you noticed this is https://github.com/Aliucord/Aliucord ? Aliucord is not related to Bunny.

Forgot to edit as bug is similarly rooted from last beta update. Still relevant to post about ? 
I know bunny is a modded client while aliucord calls web browser interface but both times it doesn't work since Beta 4

**Comment by Juby210** [comment]
I don't even understand what do you mean. It is not related to Aliucord and this repository/organization at all.

**Comment by ragxxv** [comment]
![Untitled119_20240722152005](https://github.com/user-attachments/assets/c8e4776a-1cd7-43f4-bd71-0caa397ac960)

**Comment by NeytirX** [comment]
I had to edit bunny --> aliucord. Same post otherwise.

Aliucord doesn't work on Android 15 Beta 4
