### ISSUE TITLE
App not installed on android 12

### ISSUE THREAD

**Issue by julian20yt** [Aliucord/Aliucord#467]
### What happens when the bug or crash occurs?

I cant install because "package appears to be invalid"

### What is the expected behaviour?

I expect to say "app installed" but it fails

### How do you recreate this bug or crash?

IDK

### Crash-log

```
not a crash
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
go to the support channel
