### ISSUE TITLE
Channel messages don't load after recent update

### ISSUE THREAD

**Issue by Palloxin** [Aliucord/Aliucord#468]
### What happens when the bug or crash occurs?

This appears upon opening the app:
![Screenshot_20240806-195646](https://github.com/user-attachments/assets/9dd556df-143c-4e0d-9cc1-e6bd87495681)

And channels messages are in an infinite loading loop

https://github.com/user-attachments/assets/cadc6325-b0d7-4096-a4d6-69adb1bd2ce0

### What is the expected behaviour?

chat and channel messages are loaded

### How do you recreate this bug or crash?

I just updated.

### Device
Android 8 miui 8
huawei p8 lite 2017

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
You didn't provide any logs and this is only you issue. Important coreplugin that's needed for the app to work failed to load. Do you think that I didn't even open the app to see if messages load? Go to support channel on the discord server and provide logs, as this is only you issue.
