### ISSUE TITLE
search and threads button have switched places

### ISSUE THREAD

**Issue by EnderNon** [Aliucord/Aliucord#469]
### What happens when the bug or crash occurs?

The search button and the threads button have switched somehow after moving to a new phone and copying /sdcard/Aliucord/ over.

I'm running Lineageos 21 with Magisk with Zygisk and LSPosed framework.

![Screenshot_20240808-135928_Aliucord](https://github.com/user-attachments/assets/3cf7acc2-3887-41d4-a64e-4909894fb552)

![Screenshot_20240808-135741_Aliucord](https://github.com/user-attachments/assets/915b69a2-2da9-4228-a001-838c041bb501)

### What is the expected behaviour?

Search button is next to the three other buttons on the right side menu, and threads button is at the top of main page.

### How do you recreate this bug or crash?

1. Install aliucord on new phone
2. Copy /sdcard/Aliucord/ directory to new device

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
this is the way it's supposed to be?
nothing changed

**Comment by BeeFox-sys** [comment]
I can confirm that my threads and search buttons are swapped, but i think its unintended behaviour because this causes me to often be unable to access threads in servers for some reason.

**Comment by rushiiMachine** [comment]
That could've been an old experiment
You'll have to play around and see if one of them brings back that behavior
Either way, it's not a bug
