### ISSUE TITLE
[Feature Request] Alert when a user extracts the plugin instead of dropping the zip file in the plugin folder

### ISSUE THREAD

**Issue by abUwUser** [Aliucord/Aliucord#47]
As I saw in the support channel, some new users extracts the plugins instead of dropping them. Makes sense to extract it, considering that zip files were made to be extracted.
My suggestion to fix this issue is to alert users when a folder in the plugins folder is found.

**Comment by WinstonSepruko** [comment]
I was actually planning on adding something like this soon™️

**Comment by abUwUser** [comment]
btw was this implemented?

**Comment by Vendicated** [comment]
Implemented in https://github.com/Aliucord/Aliucord/commit/15d9ba493adea2a9a6772e96b8ddc6f4e745554b
