### ISSUE TITLE
Support for Android's Material You Themed Icons

### ISSUE THREAD

**Issue by Tiberth** [Aliucord/Aliucord#472]
### What is it that you'd like to see?

The app icon should adapt to the Material You "Themed Icons" feature, changing its color palette to match the system-wide theme and wallpaper, as other compatible apps do.

### Go into more detail...

The current version of the app does not support Android's new "Themed Icons" feature, introduced with Material You. This feature allows app icons to dynamically change based on the user's wallpaper and system theme. Unfortunately, the app's icon does not conform to these changes, leading to an inconsistent user experience.

Steps to Reproduce:
1. Update to the latest version of Android that supports Material You.
2. Enable "Themed Icons" in the Android settings.
3. Observe that the app icon does not change according to the system theme.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by rushiiMachine** [comment]
this is implemented in the WIP installer
https://github.com/Aliucord/Manager/issues/66

wait for it to become the main was to install
