### ISSUE TITLE
unban new account ban

### ISSUE THREAD

**Issue by user28283sp** [Aliucord/Aliucord#474]
### Tell us all about it.

i haven't use a vpn and i tried to joij the group the account was created. so it's highly likely an new account ban. please unban me.

username: saushso13

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by Vendicated** [comment]
![image](https://github.com/user-attachments/assets/4e74813b-45d3-4c79-9a8e-e8d173da2d98)
![plinker98-catimplode](https://github.com/user-attachments/assets/f8e874db-34ad-4549-95d5-b394edf52039)
