### ISSUE TITLE
Emojis are blank

### ISSUE THREAD

**Issue by JustJustBeth** [Aliucord/Aliucord#481]
### Discord Account

JustBeth

### What happens when the bug or crash occurs?

As of yesterday (9/9/2024), all default emojis are blank. Custom emoji from servers still appear, and my phone displays keyboard emoji just fine even on Discord, but the Discord emoji themselves are blank. Screenshots provided.
Emoji in text form, before sending, along with the emoji menu and the blank circles that have taken their place.
![Screenshot_20240910-160336](https://github.com/user-attachments/assets/323fbf2e-a8f3-4a96-9aa9-6c712a752cc0)
What the message looks like after sending.
![Screenshot_20240910-160354](https://github.com/user-attachments/assets/bf619f7f-509c-4933-9b19-172e7df684a9)
Emoji from the r/Zelda server, which appear just fine.
![Screenshot_20240910-160739](https://github.com/user-attachments/assets/00f46583-4a8b-4eeb-b5ef-448828ada1ed)
Emoji in my messages app.
![Screenshot_20240910-160446](https://github.com/user-attachments/assets/3217866d-0dae-4439-9fe2-60fc2e002797)

This bug occurs all the time.
I have a Google Pixel 4a, running Android 13.

### What is the expected behaviour?

I expect the default Discord emoji to display properly, instead of being blank.

### How do you recreate this bug or crash?

I do not know how to recreate this, as it seems to be permanent. There is nothing that triggers this, it just is.

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
provide a full unfiltered logcat

**Comment by Juby210** [comment]
Update installer to 1.2.0 and reinstall. Your install is just broken because of Android update.
