### ISSUE TITLE
Keyboard emojis not showing

### ISSUE THREAD

**Issue by markrizko** [Aliucord/Aliucord#485]
### What happens when the bug or crash occurs?

It seems keyboard emojis (not discord emotes) are not shown. Just a blank space where they should be, most notably seen in reactions, but leaves an empty space in message contents as well. 

### What is the expected behaviour?

Expect keyboard emojis to be shown

### How do you recreate this bug or crash?

Have another user react to a message with an emoji from the keyboard (everyone I communicate with uses Apple devices, so it may just be Apple emojis). Screenshots attached. 
![WhatsApp Image 2024-09-16 at 21 44 34_10e1e6b9](https://github.com/user-attachments/assets/039f0001-0a12-44c8-88d2-5e2a8b1567fe)
![WhatsApp Image 2024-09-16 at 21 46 05_2572222d](https://github.com/user-attachments/assets/180f1d1b-807b-4a4a-97e0-e6c6df76a385)

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
reinstall, if doesnt work go to the support channel
