### ISSUE TITLE
not able to join

### ISSUE THREAD

**Issue by YashSoPro** [Aliucord/Aliucord#486]
### Tell us all about it.

hello, so basically i switched to vendetta than bunny(pycord) after i noticed aliucord is not updated but now i thought to come back to aliucord because it uses og version of discord but im not able to join im not using vpn anything im pretty sure im banned but i dont remember why i was banned or what i had done,i request you to unban me if i have done any mistake in past or broke any rule please forgive me. My username is SableMeow, you can check if im banned or not if im please forgive me and unban me :( i tried joining with this link discord.gg/EsNDvBaHVU.

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
you were acting like a troll
