### ISSUE TITLE
Forgive :(

### ISSUE THREAD

**Issue by YashSoPro** [Aliucord/Aliucord#487]
### Tell us all about it.

you told me my mistake but still like no unban i really want to use this again but i can't i request you to give me a last chance i won't do any inconvenience this time if i do you can ban me and that time i won't ask you to unban me because i know its my 2nd mistake

i request you to give me last chance and unban me my id is SableMeow

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
> bruh @rushii i said in issue that i won't do anything if i have done you should give me and other guys like me a another chance everyone changes themselves even theifs and cirminals
so give me a last chance as if i don't change myself go ahead ban me again 

You clearly have not changed in any way
