### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by sableduck1** [Aliucord/Aliucord#488]
### Tell us all about it.

how can you guys tell im not changed it depends on my behaviour how i act on server if i act bad or break rules even i agree i have not changed just by looking at my issues you can't tell if i have changed or not

so please i badly request you to unban me because i wanna use this app again :(
and yes im SableMeow you guys took my ability to create issues so i had to use my 2nd account

i know it was my mistake but still atleast a last chance to prove i have changed
my id: SableMeow

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by rushiiMachine** [comment]
you're acting like a fucking child
