### ISSUE TITLE
Jump To Message Plugin

### ISSUE THREAD

**Issue by Ketsuyumi** [Aliucord/Aliucord#498]
### What is it that you'd like to see?

I would like to have this plugin jump to first message of a thread

### Go into more detail...

So, I would like it as a menu option, when holding a thread, to show: "jump to first message", and by tapping that, to go to the start of said thread. Currently, there is a such plugin for just channels, can't see threads on it.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by jedenastka** [comment]
This should be in the plugin requests repo.

**Comment by Ketsuyumi** [comment]
> This should be in the plugin requests repo.

where is that?
