### ISSUE TITLE
Unban request (Account age)

### ISSUE THREAD

**Issue by siblingsofthevoid** [Aliucord/Aliucord#499]
### Tell us all about it.

I understand this isn't for unban requests, but I also haven't found any other way to request this, especially when it is regarding to account age... 

Since nothing happens when I accept the invite, I first thought the client was genuinely broken, but since it happens in all clients, the only conclusion is that I'm banned.

Why account age? I have previously used aliucord and I recreated my account due to email verification issues. And I had expected to just be able to set everything up...
I'll add my user ID once I'm on desktop.

I also recommend giving people a place to go if you don't want people to come here for this.

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by jedenastka** [comment]
https://github.com/Aliucord/ban-appeals

**Comment by siblingsofthevoid** [comment]
Thanks and I recommend to add it to the website too ^^
