### ISSUE TITLE
Vanilla discord option?

### ISSUE THREAD

**Issue by jaxankey** [Aliucord/Aliucord#502]
### What is it that you'd like to see?

Can you give us an option to just install the vanilla discord app? :) Some people have a little fear about discord's anti mod policy.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Juby210** [comment]
How is that related to *modded* Discord?
You can download not modded Discord apk and install it yourself.

**Comment by jaxankey** [comment]
I understand, but finding a reliable apk involves either some complicated extraction procedure from a phone or downloading from an unsavory source. (At least I couldn't find a "download apk" from the discord site!) 

Your sidequest installer, by contrast is SLICK and updates easily! I could even get my DAD to use it. ;)

Anyway, just a thought; keep doin your thing no worries.

**Comment by rushiiMachine** [comment]
Took me 3 seconds to find on google:
https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-126-21-stable-release/

**Comment by jaxankey** [comment]
I don't trust things from apkmirror or any other site. Who knows what they did to it. Fair enough though, I don't know where you download it from (I thought discord direct).

Anyway, instead of being short with me, feel free to just close / ignore / move on. It was just a suggestion.
________________________________

**Comment by jedenastka** [comment]
You can compare APK signatures with `apksigner`. With this, you can confirm APKMirror uses original files for all their mirrors. Other websites might be sketchy, but APKMirror was always a core part of the Android community.

You can still download the old version directly from Google Play using Aurora Store. The version code is `126921`.

Aliucord downloads the APK from it's own website to my knowledge. Discord does not host the client downloads for Android, and interfacing with Google Play is a complex task.

Not sure what's the reason to avoid Aliucord anyways, even if you don't use plugins. The client will be less broken, as there's patches that get it more up to speed with the later versions.

**Comment by rushiiMachine** [comment]
I believe we originally redirected to aptoide (another APK mirror) but once the download from there disappeared(?) we just serve the APK directly.

> Anyway, instead of being short with me, 

That's fair, my bad.

But the thing about APK signatures above is true, as long as the signature is original then it's fine regardless of where it was downloaded from.

**Comment by jaxankey** [comment]
Thanks for the feedback. My goal is to push Aliucord on everyone I know because it's so simple.

The only reason people shy away is that Discord explicitly prohibits mods in their TOS and threatens action against people using them. So far they have not pursued anyone (it does not seem in their best interest / I don't see a motivation to do so) but the risk is there if some weird market forces or other events push them.

I thought it would be just a few lines of code to give the option to not patch it but I see where you're coming from, and time is valuable.
________________________________

**Comment by dolfies** [comment]
Based on how Discord's antispam works, it's far more likely that accounts using any version of the old app—whether modded or otherwise—end up getting flagged, rather than what you're describing.

**Comment by rushiiMachine** [comment]
> I thought it would be just a few lines of code to give the option to not patch it but I see where you're coming from, and time is valuable.

The time isn't really the issue here. 
1) As Juby already said, it doesn't really make sense for a modded installer to have the option to install srock
2) The stock old app is so old that it's semi unusable without backports (which aliucord has some)

**Comment by jaxankey** [comment]
Oh interesting. I did some more reading and only now realized that Aliucord is for all android devices. I found it through Sidequest, which allows you to sideload apps onto the Meta Quest VR headsets. This is a very complex task for most, especially custom apk's etc, and you should know that Aliucord REALLY makes this process MUCH easier, bringing Discord to VR!

This is a great service you have done (perhaps inadvertently) as people have been wanting discord on Quest since they first came out!

Anyway, these were the motivations for my questions. I agree they're a little weird if I'm asking about android in general.
________________________________
