### ISSUE TITLE
Outdated Twemoji version. Doesn't support new emojis. 

### ISSUE THREAD

**Issue by treuks** [Aliucord/Aliucord#504]
### Tell us all about it.

Aliucord seemingly uses an old twemoji version, which doesn't seem to support new emojis, such as 🩷 and 🫵 . 

It would be nice if it was possible to switch the emojis to the (basically official) fork of twemoji, which is also currently used by official discord clients: https://github.com/jdecked/twemoji

### Request Agreement

- [X] I did indeed check to make sure the issue is original!

**Comment by Juby210** [comment]
Exists as a plugin called NewEmojis.
