### ISSUE TITLE
[Feature Request/Fix] The app launch times

### ISSUE THREAD

**Issue by ItsHanibee** [Aliucord/Aliucord#63]
The app launch seems to be taking a while, I don't know if it's inherently a problem with how the app and plugins function but if there's a temporary fix or anything of that sorts that'd be great! ❤️

**Comment by Vendicated** [comment]
Fixed in https://github.com/Aliucord/Aliucord/commit/6f563a98a98c3cfdfb2d0f00d4ee15e66698b57c
