### ISSUE TITLE
Crash Aliucord Comman and punctuation

### ISSUE THREAD

**Issue by WheneverDev** [Aliucord/Aliucord#68]
I am using Aliucord version 87.3 with a French keyboard.

When I use a command added by a plugin on Aliucord and after writing a punctuation character (!,?) Which added automatically to the command, the screen freezes and when I completely erase the line, Aliucord crashes.

[example video (imgur)](https://imgur.com/a/Gs448JN)

**Comment by Juby210** [comment]
Is it Aliucord's bug or Discord's 87.3? Can you reproduce it with bot slash commands on Alpha Discord?

**Comment by WheneverDev** [comment]
The same crash happens but only with plugins requiring aguments (same on Aliucord)

**Comment by Juby210** [comment]
If it's Discord's bug it doesn't belong here.
