### ISSUE TITLE
AppCloner-like Feature Request

### ISSUE THREAD

**Issue by VioletStorm** [Aliucord/Aliucord#8]
This is a suggestion for the additional functionality within the Aliucord Installer.

Since AppCloner has issues with Aliucord, and easy in-app account switching is not possible when using 2FA, I suggest the addition of a tool within the installer which allows for multiple copies of Aliucord to be installed at once.  

Additionally, having the app name and icon editable per each copy would make keeping multiple apps distinct from one another much easier.  I realize names and icons typically can be changed within a launcher, but these changes are not persistent throughout the entirety of a device.

**Comment by nearlySplat** [comment]
This would need a significant code change as the only way I would know how to do this is to loop over **every single file** in the source code and change the package name from `com.aliucord` to something else. Not only would this be resource intensive but also it would be very slow for a lot of users.

Of course, I'm not the most knowledgeable person on this matter, as I've only dabbled a bit in Java and never in an Android app.

**Comment by vy-storm** [comment]
> This would need a significant code change as the only way I would know how to do this is to loop over **every single file** in the source code and change the package name from `com.aliucord` to something else. Not only would this be resource intensive but also it would be very slow for a lot of users.
> 
> Of course, I'm not the most knowledgeable person on this matter, as I've only dabbled a bit in Java and never in an Android app.

Luckily in my limited testing it seems like AppCloner++ has started working now?  I'm not sure how things will go as far as updating and changing app settings independently though...  I really didn't test much.

The ideal solution would still be something built in at the Aliucord manager app, but hopefully things work good enough that should I ever want to make the full switch from my current client I'll be able to-

**Comment by DiamondMiner88** [comment]
this is supported in aliu manager
excluding separate plugins/plugin settings

**Comment by VioletStorm** [comment]
> this is supported in aliu manager
> excluding separate plugins/plugin settings

Where?

**Comment by DiamondMiner88** [comment]
Aliucord/AliucordManager

**Comment by VioletStorm** [comment]
> https://github.com/Aliucord/AliucordManager

Is this different from the current aliucord installer?

**Comment by DiamondMiner88** [comment]
it's a rewrite

**Comment by VioletStorm** [comment]
> it's a rewrite 

Very good! Is there a prebuilt version yet?

**Comment by DiamondMiner88** [comment]
check actions

**Comment by VioletStorm** [comment]
> check actions

I didn't see any prebuilt app but it's nice to know cloning will be in the new releace
