### ISSUE TITLE
Login as bot

### ISSUE THREAD

**Issue by itsmeboy0** [Aliucord/Aliucord#80]
Using the "Login using token" method does not work for bots. It would be great if we would be able to login as bot like in Lightcord.

**Comment by nearlySplat** [comment]
kadybat (A Discord staff) [said in the Discord Developers server][msg] that logging into a client (whether third-party or not) and using it like a human account is classified as selfbotting.

advaith, however, clarified it, but it seems kadybat's stance didn't change so IMO it's a better idea to not implement this.

[msg]: https://discord.com/channels/613425648685547541/696891424041598978/751177427685867531

**Comment by itsmeboy0** [comment]
> kadybat (A Discord staff) [said in the Discord Developers server](https://discord.com/channels/613425648685547541/696891424041598978/751177427685867531) that logging into a client (whether third-party or not) and using it like a human account is classified as selfbotting.

I'm not in the server, but I thought it was only against TOS to use bots on a user token though, and not vice versa (basically the definition of self-botting). Looked at it a bit and didn't find anything about it.

Here is the only mention of the use of bots in the community guidelines:
![image](https://user-images.githubusercontent.com/75471378/130615158-3eae41a7-704b-4870-9078-272c2afc33e9.png)

But then, the ambiguity would make this in the same grey area as modded clients but safer, as it doesn't flag bot accounts as far as I'm aware (You could add self-bots logged in as a bot would be indistinguishable from a real bot that runs the same code).

**Comment by Vendicated** [comment]
This is not only against Discord's Bot terms but would also require modifications because there are routes a bot can't use and would also be trouble with intents and so on. Thus is it out of scope for Aliucord and should rather be a plugin if anything.
