### ISSUE TITLE
Auto Update Plugin Option

### ISSUE THREAD

**Issue by hairyfred** [Aliucord/Aliucord#97]
Personally I would not use this feature, but a lot of people would
### **THIS OPTION SHOULD BE OFF BY DEFAULT**
And should have a warning about potential malicious plugin updates

**Comment by Vendicated** [comment]
![Screenshot_20210910-002138](https://user-images.githubusercontent.com/45497981/132770270-c114a1ed-bf12-467c-a77f-a1243a4ec1dc.jpg)
